### ISSUE TITLE
Observación - Comercial - Notas de venta - Nueva nota (Falta ortográfica en modal de subida de archivo)

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#142]
Dentro del modulo Comercial: Notas de venta: Nueva nota, al acceder al modal de "Subir Archivo Orden de Compra" este posee la siguiente falta ortográfica: 
Captura:
![image](https://user-images.githubusercontent.com/91085485/151045083-bd93dc01-719e-463a-b0db-f5bdb9782b03.png)

**Comment by Ditassara** [comment]
Cambios confirmados en QA y Productivo.
QA
![image](https://user-images.githubusercontent.com/56659426/183086007-01a486e9-3b7c-461a-9336-756620d6ea33.png)
Productivo
![image](https://user-images.githubusercontent.com/56659426/183085935-0285aaa1-cb71-47d9-8a83-15ef02b6cd05.png)
