### ISSUE TITLE
Observación - Portería - Registro de salida (Combobox "Planta")

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#143]
Dentro del perfil Reportería en el modulo Registro de salida en el listado de registros de salidas , en la columna "Planta" el combobox no tiene un texto predefinido como "Mostrar todos" o "Todos", simplemente está vacío, en la siguiente captura se visualiza lo mencionado: 
 Captura:
![image](https://user-images.githubusercontent.com/91085485/151046949-57f87a1a-ee69-4b3a-a199-3b9e0ebe8f26.png)

**Comment by Ditassara** [comment]
La opción sigue en blanco sin decir nada, tanto en QA como en Productivo.
QA
![image](https://user-images.githubusercontent.com/56659426/182939830-88a72054-9c92-4b15-ae8a-8263e6c2b6ef.png)
Productivo
![image](https://user-images.githubusercontent.com/56659426/182939907-ef87caa6-cbab-43f9-882b-ab7c2e026a60.png)

**Comment by sebastianmtralcal** [comment]
Solicitud atendida, se agrega texto faltante

**Comment by Ditassara** [comment]
Cambio confirmado en QA, faltaría actualización en Productivo.
QA
![image](https://user-images.githubusercontent.com/56659426/183211526-0868ada9-2542-4335-bebe-8bda70e4ac9d.png)
