### ISSUE TITLE
Observación - Portería - Registro de salida (Modal de confirmación de salida)

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#144]
Dentro del perfil Reportería en el modulo Registro de salida en el listado de registros de salidas, al confirmar la salida, el modal de confirmación posee un espacio innecesario entre el ultimo signo de interrogación y el ultimo numero antes de dicho signo, en la siguiente captura se puede visualizar:
![image](https://user-images.githubusercontent.com/91085485/151047582-beb2ae07-7c91-46a0-a653-69e8199043cb.png)

**Comment by Ditassara** [comment]
Cambios confirmados en QA y Productivo.
