### ISSUE TITLE
Observación - Ejecutivo Comercial LIM - Empresas de Transporte (Excel)

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#145]
En el perfil de Empresas de Transporte en el modulo de Empresas y transporte al descargar el Excel del listado de "Empresas Habilitadas", este en su interior no especifica que son "Empresas habilitadas".
![image](https://user-images.githubusercontent.com/91085485/151055222-2ba58d54-9f68-4400-8955-5b55e2f16493.png)
![image](https://user-images.githubusercontent.com/91085485/151055307-11ead512-2603-4350-9dea-f612d678fdc4.png)

**Comment by Russal-O** [comment]
Sin correción, se puede prestar para confusión.
![imagen](https://user-images.githubusercontent.com/83325414/182945824-8584602d-ad6f-4265-a5f4-9c37a3fe3a8a.png)

**Comment by sebastianmtralcal** [comment]
Se cambia titulo de excel

**Comment by Ditassara** [comment]
Cambios confirmados en QA, falta actualización en Producción.
