### ISSUE TITLE
Observación - Administrador - Maestros - Costos Mensuales (Combobox)

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#147]
Dentro del perfil de Administrador en el modulo de Maestros: Costos mensuales al seleccionar "Ver costos" de algún registro el modal de la visualización tiene 3 fallas, los 3 combobox están en blanco antes de su selección, esta debería decir "Todos" o algún sinónimo de este, en la siguiente imagen se puede visualizar dicha observación:   
![image](https://user-images.githubusercontent.com/91085485/151178234-c69ec2bc-dc59-4b37-b49d-2eb912084cbe.png)

**Comment by Russal-O** [comment]
acción no necesaria
