### ISSUE TITLE
Incidencia - Administrador - Empresas de Transporte - Datos Empresa de Transporte (Nuevo conductor "email" formato erróneo)

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#149]
Dentro del perfil de Administrador en el modulo de Empresas de Trasporte: Datos Empresa de transporte, el ingresar un nuevo conductor el campo de "Email" no posee el formato correcto, es decir, al introducir cualquier letra o carácter el sistema lo valida como mail, aun si no están presente los caracteres de "@" y/o algún proveedor de correo valido, en la siguiente captura se puede visualizar dicha incidencia: 
![image](https://user-images.githubusercontent.com/91085485/151183505-867b07ea-cf7b-4c60-83ec-be84191e8af2.png)

**Comment by cbastiasv** [comment]
Traté de crear un conductor con email cbastias@spsgroup.cl y test@gmail.com y el sistema me arrojaba el mensaje "el email no es válido"

**Comment by Russal-O** [comment]
QA y productivo corregido
![imagen](https://user-images.githubusercontent.com/83325414/182942321-c74b05cb-c72f-47ec-b563-833bd47d6d53.png)
