### ISSUE TITLE
Incidencia - Ejecutivo Administrativo - Informes (Histórico Notas De Venta)

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#152]
Dentro del Perfil de Ejecutivo Administrativo, dentro el modulo de Informes: Histórico Notas De Venta, el perfil tienen la posibilidad de editar los registros, esto ultimo según el manual de usuario no debe ser así, ese perfil en dicho modulo solo puede "visualizar y exportar la información" de dicho modulo.
En las siguientes capturas de puede observar la evidencia de la incidencia:

Captura del sistema con perfil Ejecutivo Administrativo:
![image](https://user-images.githubusercontent.com/91085485/152180372-7e4160fe-b76e-4956-ae52-94d12a8bb8a2.png)
Como se puede observar, el usuario con dicho perfil tienen la libertad de editar los registros.

Captura del manual de usuario:
![image](https://user-images.githubusercontent.com/91085485/152180628-0b961438-f8fc-4e7d-8b1f-2cd75a5be42b.png)
Pagina 9.

**Comment by Ditassara** [comment]
Esto fue cambiado en el manual de usuario, por lo tanto estaría correcto que pueda editar. Funciona en QA y Productivo.
Manual de usuario
![image](https://user-images.githubusercontent.com/56659426/183097608-12b9787c-7d63-41ab-8f8e-15256c233bf8.png)
