### ISSUE TITLE
Incidencia - Ejecutivo de Crédito - Comercial - Pedidos (Agregar pedido)

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#153]
Dentro del modulo de Ejecutivo de Crédito, dentro del modulo Comercial: Pedidos, dicho perfil no tiene la posibilidad de agregar un nuevo pedido, según el manual de usuario dicho perfil si debería tener esa opción. En las siguientes capturas se puede observar dicha incidencia con mas detalle:

Captura del sistema con el perfil "Ejecutivo de Crédito":
![image](https://user-images.githubusercontent.com/91085485/152182525-bafd51c1-ef75-4b2f-9015-284e13afe0b3.png)

Captura del manual de usuario:
![image](https://user-images.githubusercontent.com/91085485/152182629-704632e5-2f11-4ab6-a9ee-fea3818d4cb7.png)
Pagina 36.

**Comment by Ditassara** [comment]
Esto fue cambiado en el Manual de usuario, por lo tanto estaría correcto que no pueda agregar un pedido.
Sin embargo en el apartado de los perfiles del manual de usuario, aún dice que puede agregar, eso debe ser corregido.
Manual de usuario
![image](https://user-images.githubusercontent.com/56659426/183099981-cc90c2b1-c8bf-4d4a-96d1-d45c461619bb.png)
![image](https://user-images.githubusercontent.com/56659426/183100692-61361208-1c88-4b88-bfbd-a47f5556783b.png)
