### ISSUE TITLE
Observación - Jefe de Laboratorio (Nombres erróneos en módulos)

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#155]
Dentro el perfil de Jefe de Laboratorio, hay 2 errores en los nombres de los módulos de dicho perfil.
- El modulo que se dice "Laboratorio" debería llamarse "Informes" **(Error de redacción en el Manual de Usuario)**
- El modulo de "Informes" debería llamarse "Maestros" **(Error de redacción en el Manual de Usuario)**

Esto que se menciona está dentro del manual de usuario del sistema, en donde se puede observar el nombre correcto de dichos módulos. En las siguientes capturas se pude obtener mas detalle de dicha observación:

Captura del sistema con perfil "Jefe de Laboratorio":
![image](https://user-images.githubusercontent.com/91085485/152187486-9a5fb7b7-773b-4605-aa33-d0f0bf38fb84.png)

Captura del manual de usuario:
![image](https://user-images.githubusercontent.com/91085485/152187365-2ecc364d-f230-4146-9744-383a3d0112fd.png)

**Comment by cbastiasv** [comment]
Esto es un error de redacción en el Manual de Usuario, en la sección que enumera las funcionalidades por cada usuario (la que se ve en la imagen). En el cuerpo se llaman "Laboratorio" e "Informe". Ya se realizó la corrección del Manual de Usuario
