### ISSUE TITLE
Incidencia - Gerente de Ventas - Maestros - Costos mensuales (Exportar registros)

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#158]
Dentro del perfil de Gerente de Ventas, en el modulo de Maestros: Costos mensuales, el perfil tiene la posibilidad de exportar los registros del modulo, esto no debería pasar según el manual de usuario del sistema. En las siguientes capturas se puede visualizar dicha incidencia con mas detalle:

Captura del sistema con perfil: "Gerente de Ventas".
![image](https://user-images.githubusercontent.com/91085485/152204890-579f05ea-d30b-4154-a263-d66badc8d822.png)
Se descargaron en la imagen los registros del mes de diciembre del año 2021..

Captura del manual de usuario del sistema:
![image](https://user-images.githubusercontent.com/91085485/152205102-67f266c3-7cec-4632-8d94-5c127f1222fb.png)
Como dice el manual de usuario se puede solo "Visualizar".
Pagina 14

Captura del

**Comment by cbastiasv** [comment]
Gerente de Ventas puede exportar la información Costos Mensuales. Al parecer no se utilizó la ultima versión del Manual de Usuario. Revisado y aun puede descargar la información en Excel y CSV. Por eso se cierra.
