### ISSUE TITLE
Incidencia - Gerente Comercial - Maestros - Costos mensuales (Edición y exportación)  

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#160]
Dentro del perfil de Gerente Comercial, en el modulo Maestros: Costos mensuales, el usuario puede editar y exportar los costos mensuales, esto según el manual de usuario solamente debería tener la posibilidad de "visualizar información" de los costos mensuales. En las siguientes capturas se puede visualizar de mejor manera este incidente.

Captura del sistema con perfil "Gerente Comercial":
![image](https://user-images.githubusercontent.com/91085485/152215491-1a648691-d768-4d09-a077-915fa2225884.png)
Como se puede ver no solo permite la exportación de los datos, si no también de realizar cambios y guardarlos.

Captura del manual de usuario:
![image](https://user-images.githubusercontent.com/91085485/152219940-3ef4d926-d775-45c9-b844-5e4717e3cf39.png)
Pagina 14.

**Comment by cbastiasv** [comment]
Error en el Manual. Se utilizó una versión anterior. El Gerente Comercial puede exportar los datos de costo mensuales. Revisado y aun puede por eso se cierra.

<img width="505" alt="image" src="https://user-images.githubusercontent.com/91262348/154488758-803a0cb7-e89e-4cba-8aaa-d9bb611317e8.png">
