### ISSUE TITLE
Incidencia - Ejecutivo comercial plus - Informes - Histórico de Notas de Venta (Edición de los registros)

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#161]
Dentro del perfil Ejecutivo comercial plus, dentro del modulo Informes: Histórico de Notas de Venta, dicho perfil tiene la posibilidad de editar los registros de Nota de Ventas del sistema, esto no debe ser así, según el manual de usuario este perfil solo debería "visualizar y exportar la información" en dicho modulo. En las siguientes capturas se puede encontrar evidencia de esta incidencia:   

Captura del sistema con perfil "Ejecutivo comercial plus"
![image](https://user-images.githubusercontent.com/91085485/152224879-f4e64730-23d6-44c4-a47c-e4ad434f72c5.png)
Como se puede observar en la imagen el usuario puede editar algún de los campos subrayados en rojo.

Captura del manual de usuario.
![image](https://user-images.githubusercontent.com/91085485/152225004-59a16497-6292-4a41-a1ab-750a24fa6643.png)
Pagina 15.

**Comment by Ditassara** [comment]
Cambios confirmados en Productivo, en QA no es posible ya que no hay datos en la tabla.
QA
![image](https://user-images.githubusercontent.com/56659426/182938192-412e836f-fc5c-4e5f-a142-aa4f89bdd378.png)
Productivo
![image](https://user-images.githubusercontent.com/56659426/182938145-6e2a11c7-2372-4202-ab33-64c8f64762d2.png)
