### ISSUE TITLE
Incidencia - Ejecutivo Comercial - Informes - Histórico notas de venta (Editar)

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#162]
Dentro del perfil Ejecutivo Comercial en el modulo Informes: Histórico notas de venta, el usuario puede editar los registros de Nota de ventas, esto según el manual de usuario es erróneo, este perfil solo puede "visualizar y exportar la información" en dicho modulo.
En las siguientes capturas se puede ver la invidencia de este incidente:

Captura del sistema con perfil "Ejecutivo Comercial":
![image](https://user-images.githubusercontent.com/91085485/152347280-dbdd8672-8d95-44b6-996b-804b789c5c3e.png)
Como se puede visualizar, el usuario puede editar alguno de los campos del registro.

Captura del manual de usuario:
![image](https://user-images.githubusercontent.com/91085485/152347471-f08113fc-7c0a-441d-bc20-3cbcfc2a1f14.png)
Pagina 15/16.

**Comment by cbastiasv** [comment]
Revisado. Aún puede editar los datos de una Nota de Ventas pasada a Histórico.
<img width="1108" alt="image" src="https://user-images.githubusercontent.com/91262348/154489646-e8608a01-bb1d-47a6-8892-632ec77182c8.png">
