### ISSUE TITLE
Incidencia - Ejecutivo Comercial LIM - Informes - Histórico notas de venta (Campos habilitados en Editar)

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#163]
Dentro del perfil Ejecutivo Comercial LIM en el modulo Informes: Histórico notas de venta, el usuario tiene los campos habilitados en los registros de Nota de ventas, esto según el manual de usuario es erróneo, este perfil solo puede "visualizar y exportar la información" en dicho modulo.
En las siguientes capturas se puede ver la invidencia de este incidente:

Captura del sistema con perfil "Ejecutivo Comercial LIM":
![image](https://user-images.githubusercontent.com/91085485/152349084-69e30e03-8586-4b57-8677-13105c271ef8.png)
No se pueden guardar los cambios, pero aun así, los campos subrayados deberían estar inhabilitados. 

Captura del manual de usuario:
![image](https://user-images.githubusercontent.com/91085485/152349301-26df2399-3ed9-4738-80f1-9d605633683d.png)
Pagina 16.

**Comment by Russal-O** [comment]
QA y productivo corregido
![imagen](https://user-images.githubusercontent.com/83325414/182960604-19499928-791d-42cb-bd4b-4fbbdb97a083.png)
