### ISSUE TITLE
Incidencia - Perfiles: "Cliente Full" y "Cliente Limitado"

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#164]
Al iniciar sesión en el sistema, no se encuentran los perfiles de "Cliente Full" y "Cliente Limitado", estos según el manual de usuario debería estar dentro de los perfiles disponibles en el sistema. En las siguientes capturas se puede visualizar dicha evidencia: 

Captura del sistema:
![image](https://user-images.githubusercontent.com/91085485/152350575-aa952ccb-7c72-4b46-97d8-2f51af55ea4d.png)

Captura del manual de usuario:
 ![image](https://user-images.githubusercontent.com/91085485/152350449-40149a73-ec32-4694-a1f6-903dcdbb3163.png)

**Comment by Russal-O** [comment]
Existen otras credenciales para esos usuarios, por lo que pienso que esta incidencia fue cerrada.
