### ISSUE TITLE
Observación - Ejecutivo de Crédito - Maestros - Costos mensuales (Combobox vacío)

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#166]
Dentro del Perfil Ejecutivo de Crédito en el modulo Maestros: Costos mensuales dentro del modal de visualización de costos mensuales por año, los combobox "todos los dato" no tiene nombre y se encuentra vacío. En la siguiente captura se puede ver dicha observación: 
![image](https://user-images.githubusercontent.com/91085485/152374110-7dc80ee8-da8c-40a7-bd17-495295ac5f45.png)
En ese caso dichos combobox deberían decir en cada uno "Todos los productos", "Todas" y "Todas las plantas" o algo similar.

**Comment by Ditassara** [comment]
Sigue de la misma manera en QA y Productivo.
QA
![image](https://user-images.githubusercontent.com/56659426/183089494-37e1c2f8-a258-4911-b70a-d48a404ef377.png)
Productivo
![image](https://user-images.githubusercontent.com/56659426/183089576-dfb37e99-529e-452b-a3ac-ddf761ee1438.png)

**Comment by sebastianmtralcal** [comment]
Solicitud atendida, se eliminan los campos vacíos

**Comment by Ditassara** [comment]
Cambios confirmados en QA, falta actualización en Producción.
