### ISSUE TITLE
Observación - Jefe de Transportes - Operaciones - Programación de pedidos (Combobox)

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#168]
Dentro del perfil Jefe de Transportes en el modulo de Operaciones: Programación de pedidos , hay seis combobox dentro de dicho modulo los cuales no tienen nombre por defecto. En la siguiente captura se puede visualizar dicha observación:
Captura del sistema:
![image](https://user-images.githubusercontent.com/91085485/152394054-bc662d2c-b608-40d6-bd92-d590d0bb83a1.png)
Las columna subrayadas.

**Comment by Russal-O** [comment]
continua el error
![imagen](https://user-images.githubusercontent.com/83325414/182937041-587d1669-6357-4f02-bc48-832032b011c7.png)

**Comment by sebastianmtralcal** [comment]
Solicitud atendida, se ajusta texto y ancho de los buscadores

**Comment by Ditassara** [comment]
Cambios confirmados en QA, falta actualización en Producción.
QA
![image](https://user-images.githubusercontent.com/56659426/183216380-7da33e8c-7588-4ea7-92eb-6eb4322b7592.png)
