### ISSUE TITLE
Observaciones - Jefe de laboratorio - Laboratorio - Certificados pendientes (combobox)

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#172]
Dentro del perfil Jefe de laboratorio: Laboratorio: Certificados pendientes , hay un combobox dentro de dicho modulo los cuales no tienen nombre por defecto. En la siguiente captura se puede visualizar dicha observación:
Captura del sistema:
![image](https://user-images.githubusercontent.com/91085485/152400691-0873f8c6-ae4e-4cd2-84fa-80029aff5648.png)

**Comment by Russal-O** [comment]
módulo sigue sin título por defecto, ¿es necesario?
