### ISSUE TITLE
Observaciones - Jefe de laboratorio - Laboratorio - Gestión de certificados (combobox)

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#173]
Dentro del perfil Jefe de laboratorio: Laboratorio: Gestión de certificados , hay un combobox dentro de dicho modulo los cuales no tienen nombre por defecto. En la siguiente captura se puede visualizar dicha observación:
Captura del sistema:
![image](https://user-images.githubusercontent.com/91085485/152400916-db017c48-3bbc-4fb5-80c3-e51138103666.png)

**Comment by Russal-O** [comment]
¿cerrado por no ser necesario?
