### ISSUE TITLE
Observación - Gerente de ventas - Informes - Notas de Venta y Márgenes (Texto en ingles)

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#174]
Dentro del perfil Gerente de ventas en el modulo Informes: Notas de Venta y Márgenes, debajo de el listado de registros se encuentran 2 textos en ingles. En la siguiente captura se puede ver dicha observación: 
  
![image](https://user-images.githubusercontent.com/91085485/152403824-7f8243e0-6762-4127-95cd-b0090ad34b32.png)

**Comment by Russal-O** [comment]
QA y productivo corregido
![imagen](https://user-images.githubusercontent.com/83325414/182948103-9fa2aee0-b115-4adb-a707-31c044c0404e.png)
