### ISSUE TITLE
Informes - Notas de Venta y Márgenes (Gerente de Ventas)

### ISSUE THREAD

**Issue by cbastiasv** [rhasbun1/qlnow#178]
Página no tiene acento

<img width="464" alt="image" src="https://user-images.githubusercontent.com/91262348/154491353-322e3825-3b10-4d40-b106-2f02ff891755.png">

**Comment by Ditassara** [comment]
Cambio confirmado en QA y Productivo.
QA
![image](https://user-images.githubusercontent.com/56659426/182951488-1d1669af-571f-469c-8d38-4ccbb861bb38.png)
Productivo
![image](https://user-images.githubusercontent.com/56659426/182951538-4f6fc8d6-a48f-43e4-b850-610f436a915c.png)
