### ISSUE TITLE
Maestros - Empresas de Transporte

### ISSUE THREAD

**Issue by cbastiasv** [rhasbun1/qlnow#179]
El contador de Empresas de Transporte dice Clientes

<img width="1098" alt="image" src="https://user-images.githubusercontent.com/91262348/154492491-d64148a8-b687-40c0-9c28-b85080df8f93.png">

**Comment by Ditassara** [comment]
Cambios confirmados en QA y Productivo.
QA
![image](https://user-images.githubusercontent.com/56659426/182944946-408238c9-f51e-4e11-9542-52440c99c492.png)
Productivo
![image](https://user-images.githubusercontent.com/56659426/182945013-48aaa66c-e7c3-483c-81f1-511cf0870b43.png)
