### ISSUE TITLE
Empresas de Transporte - Nuevo Conductor

### ISSUE THREAD

**Issue by cbastiasv** [rhasbun1/qlnow#180]
Falta acento en la palabra Válido del mensaje que muestra el sistema al ingresar un email no válido.

<img width="348" alt="image" src="https://user-images.githubusercontent.com/91262348/154494220-78b471d1-4381-4322-956d-21ae0b03676f.png">

**Comment by Ditassara** [comment]
Cambios confirmados en QA y Productivo.
QA
![image](https://user-images.githubusercontent.com/56659426/182952635-6479ab36-ea4f-43be-94b0-1e8621d9f2b7.png)
Productivo
![image](https://user-images.githubusercontent.com/56659426/182952679-0123904f-3e79-4503-8328-65848a7fa58b.png)
