### ISSUE TITLE
Maestro Obras y Plantas (Clientes)

### ISSUE THREAD

**Issue by cbastiasv** [rhasbun1/qlnow#181]
Al Agregar una obra/planta el sistema muestra un mensaje que dice "Se Actualizó la Obra", siendo que esta está siendo creada y debería decir algo como "Obra/Planta Creada" o algo similar

<img width="228" alt="image" src="https://user-images.githubusercontent.com/91262348/154571291-843ae874-c3f2-44a2-a158-f4e7e8a59b89.png">

**Comment by Ditassara** [comment]
Se confirma cambios en QA, en Productivo no se puede corroborar por seguridad.
QA
![image](https://user-images.githubusercontent.com/56659426/182943804-ce4df7bb-de4d-4b9c-9032-be54fc5513a4.png)
