### ISSUE TITLE
Informes - Despachos por Año

### ISSUE THREAD

**Issue by cbastiasv** [rhasbun1/qlnow#182]
Aparecen textos en inglés.

<img width="341" alt="image" src="https://user-images.githubusercontent.com/91262348/154686116-fc96898e-fa1b-44f8-83c8-19006ef0a370.png">
<img width="141" alt="image" src="https://user-images.githubusercontent.com/91262348/154686166-c151fb9a-b80e-4ec9-890d-c89374398181.png">

**Comment by Ditassara** [comment]
Sigue apareciendo texto en en inglés en QA y Productivo. Dice "items" y debería decir algo como "registros".

QA
![image](https://user-images.githubusercontent.com/56659426/182950394-43cabea4-c4c8-49ac-a21d-45990e6523be.png)
Productivo
![image](https://user-images.githubusercontent.com/56659426/182950444-2cc5bab2-a15e-49ac-a98f-96bc3f6523f6.png)

**Comment by sebastianmtralcal** [comment]
Solicitud atendida , se cambia nombre por registros

**Comment by Ditassara** [comment]
Sigue diciendo "item" cuando no hay registros para mostrar.
![image](https://user-images.githubusercontent.com/56659426/183502357-a5a3c6a3-eeed-497b-a3f6-1a7b74fe0e5a.png)
![image](https://user-images.githubusercontent.com/56659426/183502388-cc1fa3f9-3bea-4324-890e-9db0be913a89.png)

**Comment by sebastianmtralcal** [comment]
no fue posible cambiar el nombre Item cuando tiene 0 datos, sin embargo este si cambiará cuando contenga 1 dato o mas
