### ISSUE TITLE
Pedidos Pendientes de Preaprobación - Excel

### ISSUE THREAD

**Issue by cbastiasv** [rhasbun1/qlnow#183]
El excel tiene por nombre y titulo Pedidos en Proceso. Las columnas que se ven en el excel son distintas a las que muestra la tabla en el sistema.

<img width="763" alt="image" src="https://user-images.githubusercontent.com/91262348/154689413-25069573-8f0e-4c91-b8bd-169c929fc4c9.png">
<img width="1100" alt="image" src="https://user-images.githubusercontent.com/91262348/154689512-af08d1de-296e-4baa-89e1-7a1e08f5860f.png">

**Comment by Ditassara** [comment]
El excel sigue teniendo por nombre "Pedidos en Proceso" y contiene una columna extra ("Total c/IVA") a la tabla que muestra el sistema. Esto pasa en QA, en Productivo no es posible corroborar ya que no hay pedidos pendientes de preaprobación.

QA
![image](https://user-images.githubusercontent.com/56659426/182948940-da26f68d-69c7-446f-9016-6d6985f82984.png)
![image](https://user-images.githubusercontent.com/56659426/182949043-efeb3946-822d-46d7-a69f-a28c07715ab9.png)

**Comment by sebastianmtralcal** [comment]
Se cambia titulo por Pedidos Pendientes de Preaprobación  y e eliminan dos columnas, la que esta vacia y la que dice total c/IVA

**Comment by Ditassara** [comment]
Sigue descargando el mismo Excel, con el nombre y la columna mencionada anteriormente. Esto lo probé con el perfil Gerente Comercial.

**Comment by Ditassara** [comment]
Cambios confirmados en QA, falta actualización en productivo.

**Comment by Ditassara** [comment]
No se puede corroborar en Producción ya que no hay pedidos pendientes de preaprobación.
