### ISSUE TITLE
Laboratorio - Certificados Pendientes - Subir Certificado

### ISSUE THREAD

**Issue by cbastiasv** [rhasbun1/qlnow#187]
Al intentar subir un certificado, el sistema lanza un error.

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/91262348/154711578-49ead1da-a3ec-457f-9ad2-59581efc683f.png">

**Comment by Ditassara** [comment]
Cambios confirmados, permite subir el certificado sin problemas en QA, en Productivo no se puede corroborar por seguridad.

QA
![image](https://user-images.githubusercontent.com/56659426/182955230-c0c4d83c-470b-4313-a3ed-675d3f3ee079.png)
![image](https://user-images.githubusercontent.com/56659426/182955294-690c8d32-6973-4b8e-8e82-6d5351649a4c.png)
