### ISSUE TITLE
Incidencia - Ejecutivo de Crédito - Pedidos (Agregar Nuevo Pedido)  

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#207]
En el usuario Ejecutivo de Crédito dentro del modulo Comercial: Pedidos, el usuario no tiene permiso de agregar un nuevo pedido en el sistema, siendo que esto no debe ser así según el manual de usuario en el cual se especifica que este usuario puede "Puede visualizar, agregar, editar, eliminar y/o exportar información" de este modulo.
En las siguientes capturas se encuentran las evidencias de esta incidencia: 
Manual de Usuario:
![image](https://user-images.githubusercontent.com/91085485/155333624-7827a19d-a73a-4eb7-8cca-1ace5f55d72a.png)
Pagina 10.

Sistema: 
![image](https://user-images.githubusercontent.com/91085485/155333534-898a6e15-1c76-42d1-a8d2-7334083b1cd8.png)

**Comment by Ditassara** [comment]
Esto fue cambiado en el Manual de usuario, por lo tanto estaría correcto que no pueda agregar un pedido.
Sin embargo en el apartado de los perfiles del manual de usuario, aún dice que puede agregar, eso debe ser corregido.
Manual de usuario
![image](https://user-images.githubusercontent.com/56659426/183099981-cc90c2b1-c8bf-4d4a-96d1-d45c461619bb.png)
![image](https://user-images.githubusercontent.com/56659426/183100692-61361208-1c88-4b88-bfbd-a47f5556783b.png)
