### ISSUE TITLE
Incidencia - Ejecutivo de Crédito - Próximos Pedidos (Granel) (Guía de despacho) 

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#209]
En el usuario Ejecutivo de Crédito en el modulo Comercial: Pedidos: Próximos Pedidos (Granel), al intentar descargar alguna guía de despacho de alguno de los registros, esta no se descarga.   
![image](https://user-images.githubusercontent.com/91085485/155334678-9622d57a-b7bc-448c-b067-9112a268f422.png)

**Comment by Russal-O** [comment]
Qa y productivo: No puedo corroborar ya que no existen datos en la tabla
![imagen](https://user-images.githubusercontent.com/83325414/183119486-5398da66-d536-4b26-b88c-cac99c0ef2c4.png)
