### ISSUE TITLE
Indecencia - Jefe de Transportes - Programación de Pedidos - Próximos Pedidos (Granel) (Ventana emergente) 

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#217]
En el perfil de Jefe de Transportes dentro del modulo Operación: Programación de Pedidos, al presionar el botón para visualizar Próximos pedidos (Granel) el sistema carga dicha pantalla pero en una ventana emergente y no en la misma ventana. En el siguiente GIF se puede visualizar dicha incidencia: 
![MALO](https://user-images.githubusercontent.com/91085485/155357595-d744338f-bb58-4fcb-9f7c-b5156c7064aa.gif)

**Comment by Ditassara** [comment]
Esto sigue ocurriendo para el perfil Jefe de Transportes y también en otros perfiles como Jefe de laboratorio, Jefe de Turno, Jefe de Bodega, Jefe de Planta (adm. externa) y Jefe de Planta (adm. Directa). Esto ocurre en QA y Productivo.
