### ISSUE TITLE
R225 Crear Pedido:

### ISSUE THREAD

**Issue by nataliabastias** [rhasbun1/qlnow#291]
Al crear un pedido en formato otro de forma repetitiva para la misma nota de venta, aparece preseleccionado una planta de origen que no corresponde a la indicada en la nota de venta.

![image](https://user-images.githubusercontent.com/91262410/158198573-a0fd4df4-cdce-49cc-8b8c-45e4f0f297ad.png)

![image](https://user-images.githubusercontent.com/91262410/158198763-5ab87684-8d29-4989-9f3d-e71ff11ec1ae.png)

**Comment by Ditassara** [comment]
Funciona sin problemas en QA, en productivo no se puede corroborar.
