### ISSUE TITLE
R242 Suspender Pedidos: OBS Roberto: Caso de 1 pedido con 1 producto, no debe aparecer la opción "cerrar pedido" si el producto ya tiene guía emitida. 

### ISSUE THREAD

**Issue by nataliabastias** [rhasbun1/qlnow#293]
Natalia:  
Aparece el botón "Cerrar Pedido" en los pedidos con guía asignada En formato:
Granel Normal - Retira 
Otros 1 Producto - Retira

![image](https://user-images.githubusercontent.com/91262410/158398941-08f019a1-b54c-4747-a374-99ba5e12b2ca.png)

![image](https://user-images.githubusercontent.com/91262410/158399008-492f1081-68ca-406b-81e9-68665dad38c4.png)

![image](https://user-images.githubusercontent.com/91262410/158399444-80b0e287-7e48-49dc-a644-5916a0550640.png)

**Comment by Ditassara** [comment]
Cambios aplicados y funcionando en QA y Productivo.
