### ISSUE TITLE
R509r Maestro Producto OBS Roberto  1)  Según comentarios del 08/11/21: Ninguna casilla debe venir preseleccionada o con algún dato por defecto, si no que debe obligar al usuario a seleccionar/ingresar, aunque sea 0. Así se evitan errores al ingresar productos (se debe mantener obligatoriedad de todos los datos)

### ISSUE THREAD

**Issue by nataliabastias** [rhasbun1/qlnow#294]
Natalia:
Permite crear pedidos sin "planta de Origen" y   "solicita certificado", el producto creado se logra visualizar en la pantalla , si se actualiza la pagina desaparece el producto.

![image](https://user-images.githubusercontent.com/91262410/158406669-5c2ac2dd-b718-48c3-b6b4-20a8e632db7e.png)

![image](https://user-images.githubusercontent.com/91262410/158406561-86abbe2a-15c2-474c-b340-65610fd10d2a.png)

**Comment by Ditassara** [comment]
Cambios corroborados, aparece un mensaje para ingresar los datos faltantes, en QA, Productivo no se comprueba por seguridad.
