### ISSUE TITLE
R509r Maestro Producto OBS Roberto  1)  Según comentarios del 08/11/21: Ninguna casilla debe venir preseleccionada o con algún dato por defecto, si no que debe obligar al usuario a seleccionar/ingresar, aunque sea 0. Así se evitan errores al ingresar productos (se debe mantener obligatoriedad de todos los datos)

### ISSUE THREAD

**Issue by nataliabastias** [rhasbun1/qlnow#295]
Natalia:
Precio de Referencia indica por defecto 0

![image](https://user-images.githubusercontent.com/91262410/158406785-02ea81ab-80a6-48e4-967b-609e52951900.png)

**Comment by Ditassara** [comment]
Cambios confirmados en QA y Productivo, pero aparece texto en inglés pidiendo insertar un valor ("Enter Value").

QA
![image](https://user-images.githubusercontent.com/56659426/182916072-684b39e3-36e8-47b7-9423-8059abdf8664.png)
Productivo
![image](https://user-images.githubusercontent.com/56659426/182916142-64f39760-acff-4aab-b963-203ced828676.png)

**Comment by sebastianmtralcal** [comment]
Se elimina el mensaje en inglés

**Comment by Ditassara** [comment]
Cambios confirmados en QA, falta actualización en Producción.
