### ISSUE TITLE
R549  Pedidos Despachados Los pedidos "despacho parcial" que ya están en histórico de pedidos, no deben contar con el botón "cerrar pedido" al abrir el pedido ¿tiene alguna función que quizás no esté considerando?

### ISSUE THREAD

**Issue by nataliabastias** [rhasbun1/qlnow#300]
Los pedidos Despachados parcial en formato Otro con forma de entrega en obra o retira  con mas de un producto y uno de ellos despachados aparece el botón "Cerrar Pedido"

![image](https://user-images.githubusercontent.com/91262410/158435208-5b50873c-1d0e-4fe9-be44-8836bf91af60.png)

**Comment by Russal-O** [comment]
Sigue apareciendo botón "cerrar pedido"
![imagen](https://user-images.githubusercontent.com/83325414/182936473-1c7e2fba-e6b2-4665-9d12-bac099e92e59.png)

**Comment by sebastianmtralcal** [comment]
Solicitud atendida, en el procedimiento almacenado se corrobora la ejecucion correcta de la solicitud, por lo que posiblemente hay pedidos que no se actualizaron bien despues de que se hizo el cambio en el procedimiento almacenado

**Comment by Ditassara** [comment]
Cambios confirmados en QA, falta actualización en Producción.
