### ISSUE TITLE
R563 - Jefe de Planta (Adm. Ext - Int) - Filtros en módulo de Programación de Pedidos

### ISSUE THREAD

**Issue by ramadanStm** [rhasbun1/qlnow#302]
El filtrado de datos no funciona correctamente. Específicamente en el filtro por fecha de carga. 

El reordenamiento de los datos en el listado está OK, tanto por orden alfabético como por fechas.

![image](https://user-images.githubusercontent.com/91633287/158477689-03d980f8-b1c5-488b-a630-ebad9a888c21.png)

**Comment by Ditassara** [comment]
El filtro funciona pero cuenta los registros que no tienen fecha de carga y los muestra igualmente, en QA y Productivo.
QA
![image](https://user-images.githubusercontent.com/56659426/183124105-63f26163-dfe6-4656-9901-e264377f70d1.png)
![image](https://user-images.githubusercontent.com/56659426/183124155-824c672c-a916-4851-bb2a-87c1d69c8e7a.png)
Productivo
![image](https://user-images.githubusercontent.com/56659426/183124195-9bc32d9c-f1c4-46cc-a023-c7892dc33a64.png)

**Comment by sebastianmtralcal** [comment]
Se arregla el SP spGetProductosconPedidoPendientePorFechaCarga

**Comment by sebastianmtralcal** [comment]
Problema resuelto

**Comment by sebastianmtralcal** [comment]
Se modifica consulta spGetProductosconPedidoPendientePorFechaCarga en base de datos y se ajustan variables en js

**Comment by Ditassara** [comment]
Cambios confirmados en QA y Productivo.
