### ISSUE TITLE
[BUG] R580 - Administrador - Maestro Clientes - Listado de Clientes no muestra campo CS en ocasiones

### ISSUE THREAD

**Issue by ramadanStm** [rhasbun1/qlnow#304]
Al momento de cargar los datos del listado de clientes, existen filas que no muestran el dato código Softland (IMG_1). No obstante, si uno edita el cliente en cuestión, sí se visualiza el CS asignado (IMG_2), pero al momento de guardar los datos sin haber editado nada, el sistema emite la siguiente alerta de error (IMG_3).

IMG_1
![image](https://user-images.githubusercontent.com/91633287/158618231-8e0f9a09-1032-4b83-bad5-d41ae338cb7a.png)

IMG_2
![image](https://user-images.githubusercontent.com/91633287/158618399-e717c3a9-ce1a-4c03-9e0d-009c7fd3525f.png)

IMG_3
![image](https://user-images.githubusercontent.com/91633287/158618484-6ac51149-f240-4d2a-b187-946b26b7ad3b.png)

**Comment by Ditassara** [comment]
Según se explica en incidencia #316, esto es porque el cliente no cuenta con CS, y el que muestra es el rut para facilitar modificación.
