### ISSUE TITLE
R583 - Perfiles Cliente - Dashboard - Pedidos En Proceso - Pedidos Despachados - Los valores reflejados en el Dashboard no son los mismos que se listan al seleccionar el módulo

### ISSUE THREAD

**Issue by ramadanStm** [rhasbun1/qlnow#305]
1.- Al seleccionar los pedidos en proceso en el Dashboard de los perfiles Cliente se listan todos los pedidos sin filtrar por estado de pedido (suspendido, pendiente VB Crédito, aprobado, etc.). (IMG_1; IMG_2).

2.- Al seleccionar los pedidos despachados, la cantidad de despachos que se visualizan en el Dashboard no es la misma que se lista al seleccionar el módulo. (IMG_1; IMG_3).

IMG_1
![image](https://user-images.githubusercontent.com/91633287/158624948-d00ad478-ccf5-4601-a971-ab1cc72c81f6.png)

IMG_2
![image](https://user-images.githubusercontent.com/91633287/158625107-7dd052fd-fc96-431c-bb9b-d267cb5dac5f.png)

IMG_3
![image](https://user-images.githubusercontent.com/91633287/158625206-65fb567a-b042-4e58-b98e-97ebddc4a60f.png)

**Comment by Ditassara** [comment]
Datos mostrados en dashboard Pedidos en Proceso junto con su módulo coinciden, los datos de dashboard Pedidos Despachados junto a su módulo también, solo que vienen filtrados a la semana en curso de manera automática, para ver todos los registros hay que quitar el filtro.
