### ISSUE TITLE
[Error] Ejecutivo Administrativo - Comercial - Módulo Notas de Venta - Botón de selección de filas a listar duplicado

### ISSUE THREAD

**Issue by ramadanStm** [rhasbun1/qlnow#306]
Al listar los elementos en el módulo se identificó que el botón "Mostrar (x) filas" está duplicado (IMG_01).

IMG_01
![image](https://user-images.githubusercontent.com/91633287/159033955-009f6400-5768-4c31-a653-a3763cb9b3fd.png)

**Comment by Ditassara** [comment]
Cambios confirmados en QA y Productivo.
QA
![image](https://user-images.githubusercontent.com/56659426/183125186-feb56f0f-8ec4-4db7-b86b-aa91d2a1ed82.png)
Productivo
![image](https://user-images.githubusercontent.com/56659426/183125251-dd9b029a-a746-4338-ac94-ce4a0226c1e5.png)
