### ISSUE TITLE
R563 No funciona bien el reordenamiento del listado por horarios (fecha de creación, fecha de entrega, etc). Ver mismo requerimiento con todos los otros listados, como el histórico de pedidos, y otros. Para todos los perfiles.

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#312]
Dentro del perfil Jefe de transporte, en el modulo Programación de pedidos, en Pedidos aprobados aun no se corrigen el ordenamiento de las fechas, en la sigueinte imagen se puede observar que "Fecha de Entrega" no ordena bien lo días, este no contempla el orden del mes y del año, lo mismo pasa con la columna "Fecha Creación". 
![image](https://user-images.githubusercontent.com/91085485/161844741-d6124f8e-c428-4423-abb4-df400195f019.png)

**Comment by RaisoProg** [comment]
seleccionen fecha

**Comment by Russal-O** [comment]
QA y productivo filtros funciona correctamente
![imagen](https://user-images.githubusercontent.com/83325414/182961916-ef413f2e-d039-49b4-8549-029804d63427.png)
