### ISSUE TITLE
R576 El Dashboard "pedidos pendientes de preaprobación" cuenta más de una vez un pedido si tiene más de 1 producto. Corregir. REvisar resto de Dashboard que cuentan pedidos para que no ocurra lo mismo.

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#313]
Aun se pueden ver mas de una copia de un pedido, si en este caso se conversó con el cliente para descargarlo por favor comentar dentro de la incidencia: 
![image](https://user-images.githubusercontent.com/91085485/161846301-68277be3-74c4-4353-a15a-144a66fd1184.png)

**Comment by RaisoProg** [comment]
contador
