### ISSUE TITLE
R577 El perfil cliente debe ver los pedidos tal como en la pantalla de pedidos en proceso. Nunca se pidió la vista consolidada. Deben verse mismas columnas que en pedidos en proceso.

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#314]
Aun no están las mismas columnas en el dashboard como lo están en el modulo "Pedidos en Proceso" como lo desea el cliente, si en este caso se descarta por favor comentarlo en esta misma incidencia.

Columnas del dashboard:
![image](https://user-images.githubusercontent.com/91085485/161847131-5d1954ce-971f-474c-8b63-f5fd77b5cad9.png)

Modulo "Pedidos en Proceso":
![image](https://user-images.githubusercontent.com/91085485/161847188-5e26d6b2-0be8-456e-8ee0-b3a85e32b58d.png)

**Comment by RaisoProg** [comment]
no confundamos clientes con empleados
