### ISSUE TITLE
R578 En la pantalla de creación de pedido, cambiar " Precio Reajustado ($**) " por "Precio Reajustado ($)* "  La nota de abajo, debe reemplazarse (**) por (*).

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#315]
Aun no está implementado, en el sistema está de la siguiente forma: Reajustado($*), sin embargo el cliente lo quiere de esta forma: Reajustado($)*, ósea que el símbolo * esté fuera el paréntesis de la derecha. 
![image](https://user-images.githubusercontent.com/91085485/161847783-9c101214-811a-4807-94d0-5cd65e66a556.png)

**Comment by RaisoProg** [comment]
*

**Comment by Russal-O** [comment]
QA y productivo ok
![imagen](https://user-images.githubusercontent.com/83325414/183098498-d753b662-3986-46ae-ac80-6e33fcb86573.png)
