### ISSUE TITLE
Perfil Ejecutivo Comercial - Clientes (No aparece el código Softland en el registro)

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#316]
Dentro del modulo Maestros: Clientes, dentro de los registros se puede observar que en algunos clientes no carga el código softland, pero al editar este código aparece en el modal de edición: 
Imagen del registro
![image](https://user-images.githubusercontent.com/91085485/161849926-116a6b41-35b9-4afe-85f2-28101044f402.png)

Imagen del modal de edición:
![image](https://user-images.githubusercontent.com/91085485/161850003-11b7738d-891a-429f-96ab-46216306f175.png)

**Comment by RaisoProg** [comment]
no tiene codigo softland ese es el rut asignado para facilitar la modficacion
