### ISSUE TITLE
PRODUCTIVO - R578 En la pantalla de creación de pedido, cambiar " Precio Reajustado ($**) " por "Precio Reajustado ($)* "  La nota de abajo, debe reemplazarse (**) por (*).

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#320]
![image](https://user-images.githubusercontent.com/91085485/161984755-1a7925bd-594a-4d50-807a-60db23831295.png)
![image](https://user-images.githubusercontent.com/91085485/161984832-68de5d0d-e889-4682-8f80-fe5700030fda.png)
Prueba realizada en el perfil: "Ejecutivo Administrativo"

**Comment by RaisoProg** [comment]
si esta el *

**Comment by Russal-O** [comment]
Ejecutivo administrativo
Qa y Productivo: comercial/pedidos/nuevo pedido/ver nota de venta: símbolo a la izquierda
![imagen](https://user-images.githubusercontent.com/83325414/183109905-44cbf520-ddf6-499d-b8e5-8c6a9c74ee38.png)

**Comment by sebastianmtralcal** [comment]
Solicitud atendida, se cambia el lugar de la simbologia

**Comment by Ditassara** [comment]
Cambios confirmados en QA, falta actualización en Producción.
