### ISSUE TITLE
PRODUCTIVO R577 El perfil cliente debe ver los pedidos tal como en la pantalla de pedidos en proceso. Nunca se pidió la vista consolidada. Deben verse mismas columnas que en pedidos en proceso.

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#322]
Aun "Pedidos Pendientes de Preaprovación" no tiene las mismas columnas que "Pedidos en Proceso", en este caso en "Pedidos Pendientes de Preaprovación" falta la columna de transporte. 

Pedidos en Proceso:
![image](https://user-images.githubusercontent.com/91085485/161987506-0d5de20a-3992-404d-ade0-4ca0b6d72915.png)

Pedidos Pendientes de Preaprovació: 
![image](https://user-images.githubusercontent.com/91085485/161987635-fc38f59a-f37f-4f3b-871f-d68321059435.png)

Prueba realizada con perfil: ""Cliente Full".

**Comment by RaisoProg** [comment]
en el mismo requerimiento dice que no quieren esa tabla en especifico
