### ISSUE TITLE
PRODUCTIVO R563 No funciona bien el reordenamiento del listado por horarios (fecha de creación, fecha de entrega, etc). Ver mismo requerimiento con todos los otros listados, como el histórico de pedidos, y otros. Para todos los perfiles.

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#324]
Aun la columna "Fecha creación" no ordena la fecha de manera correcta
![image](https://user-images.githubusercontent.com/91085485/162016459-14a537d9-c3a4-49e8-bca2-ea0c31859dd8.png)

Prueba Realizada con el perfil: "Jefe de Planta (Adm. Directa)"

**Comment by RaisoProg** [comment]
por multiples fechas no se puede ordenar ej hay fecha con am, fecha con minutos y fecha con horas

**Comment by Ditassara** [comment]
Las fechas se ordenan correctamente en QA y Productivo.
QA
![image](https://user-images.githubusercontent.com/56659426/182886988-93a227ab-e946-4e7b-8a52-d30bdce26888.png)
Productivo
![image](https://user-images.githubusercontent.com/56659426/182887076-664e1507-21f4-4e72-bebf-53160f8aea5c.png)
