### ISSUE TITLE
PRODUCTIVO R571 Los reportes de despachos están agrupando los datos por fecha de salida de los pedidos, y debe ser por fecha de la guía de despacho (fecha emisión). Corregir.

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#325]
Aun no está implementado el filtro por fecha de la guía de despacho, en este caso filtra automáticamente por "Filtro por Fecha de Salida (NO se incluyen pedidos suspendidos)", *si esto fue descartado por el cliente comentar dentro de la incidencia*
![image](https://user-images.githubusercontent.com/91085485/162023258-16d442cf-6e81-4265-90c4-15a5c006fc78.png)
Prueba realizada con perfil: "Jefe de Planta (Adm. Directa)".

**Comment by RaisoProg** [comment]
descartado por cliente
