### ISSUE TITLE
PRODUCTIVO -Incidencia - Perfil Ejecutivo Comercial - Clientes (No aparece el código Softland en el registro)

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#326]
Dentro del modulo Maestros: Clientes, dentro de los registros se puede observar que en algunos clientes no carga el código softland, pero al editar este código aparece en el modal de edición:
Imagen del registro
![image](https://user-images.githubusercontent.com/91085485/162024236-0ff70869-0eb0-4224-807d-5c5658393646.png)

Imagen del modal de edición:
![image](https://user-images.githubusercontent.com/91085485/162024329-021cd298-9749-4ad3-ada5-e47de296c80d.png)

**Comment by RaisoProg** [comment]
esto es por que por defecto si no tiene codigo softland le carga automatico el rut pero no significa que esta guardado
