### ISSUE TITLE
Gerente Comercial - Costos Mensuales

### ISSUE THREAD

**Issue by cbastiasv** [rhasbun1/qlnow#331]
Gerente Comercial tiene los controles para guardar los costos de un mes pero no puede ingresar datos en los campos

<img width="665" alt="image" src="https://user-images.githubusercontent.com/91262348/163266823-d1912484-c59e-4d2c-94ff-7e44bace4777.png">

**Comment by Ditassara** [comment]
Funciona sin problemas en QA, en Productivo no es posible corroborar por precaución.
