### ISSUE TITLE
Costos Mensuales - Nombre Mes

### ISSUE THREAD

**Issue by cbastiasv** [rhasbun1/qlnow#333]
Al agregar un mes este queda con mayúsculas (al refrescar manualmente la vista cambia a minúsculas)

<img width="430" alt="image" src="https://user-images.githubusercontent.com/91262348/163267715-58cf3bae-12dd-4b1b-a7fd-af20c951acec.png">

**Comment by Ditassara** [comment]
Cambio confirmado, queda en minúscula automáticamente. En QA, en Productivo no se puede corroborar por seguridad.
QA
![image](https://user-images.githubusercontent.com/56659426/182962067-6b769237-0bb4-40b3-b543-f125ea5483e5.png)
