### ISSUE TITLE
Modificar Pedido - Flete Falso

### ISSUE THREAD

**Issue by cbastiasv** [rhasbun1/qlnow#337]
Al presionar No en el mensaje, este no se cierra (pedidos normal y mixto)

<img width="345" alt="image" src="https://user-images.githubusercontent.com/91262348/163449329-a1a8383d-44f5-4186-9884-d8087144797f.png">

**Comment by Ditassara** [comment]
Funciona sin problemas en QA, en productivo no se puede corroborar por precaución.

QA

https://user-images.githubusercontent.com/56659426/182904074-e440ec9c-8082-40f3-85b4-6afcd445ceef.mp4
