### ISSUE TITLE
Costos Mensuales - Nuevo Mes

### ISSUE THREAD

**Issue by cbastiasv** [rhasbun1/qlnow#339]
Al agregar un mes este no se ordena en el listado, queda al final del año correspondiente (antes esto estaba bien)

<img width="563" alt="image" src="https://user-images.githubusercontent.com/91262348/163450322-787aa113-8952-49c7-8945-bf1cad1d5821.png">

<img width="363" alt="image" src="https://user-images.githubusercontent.com/91262348/163450452-d1e8e5d5-90e7-499a-8896-22c06d678f3b.png">

**Comment by Ditassara** [comment]
Funciona correctamente en QA, en Productivo no se puede corroborar por precaución.
