### ISSUE TITLE
PRODUCTIVO - R563 No funciona bien el reordenamiento del listado por horarios (fecha de creación, fecha de entrega, etc). Ver mismo requerimiento con todos los otros listados, como el histórico de pedidos, y otros. Para todos los perfiles.

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#341]
Aun  la columna Fecha de Creación no se ordena de manera correcta al organizarla de manera ascendente y descendente, 
en la siguiente captura se pude observar lo mencionado, si se observa el orden de fecha esta no coincide con un orden. 
![Captura web_18-4-2022_11641_qlnow quimicalatinoamericana cl](https://user-images.githubusercontent.com/91085485/163828682-495b3d61-4175-4f74-ab67-7ceb735ddffc.jpeg)

**Comment by dgroes** [comment]
Aun no está el cambio

**Comment by Russal-O** [comment]
Funciona ascendente y descendente

![imagen](https://user-images.githubusercontent.com/83325414/182721976-f027f303-740a-44a4-bb59-84a2887e1b14.png)
