### ISSUE TITLE
PRODUCTIVO - Observación - Notas de Venta Cerradas (Texto en ingles)

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#346]
Dentro del modulo Costo Flete y Tiempo de Traslado (Notas de Venta Cerradas) se encuentra texto en ingles que debe ser cambiado, en la siguiente captura se puede observar lo mencionado:
![image](https://user-images.githubusercontent.com/91085485/164091940-448ba8b9-b854-41ca-b04b-614665b7a7e4.png)

_Se utilizó el perfil Administrador cuando se detectó esta incidencia/observación._

**Comment by RaisoProg** [comment]
pantalla obsoleta la cual será modificada con el sow de fletes y distancia
