### ISSUE TITLE
PRODUCTIVO - Observación - Asignaciones Pendientes (Texto en ingles)

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#347]
Dentro del modulo Costo Flete y Tiempo de Traslado (Asignaciones Pendientes) se encuentra texto en ingles que debe ser cambiado, en la siguiente captura se puede observar lo mencionado:

![image](https://user-images.githubusercontent.com/91085485/164092196-9862b3cf-c034-49bc-b543-be1e0687d147.png)

_Se utilizó el perfil Administrador cuando se detectó esta incidencia/observación._

**Comment by RaisoProg** [comment]
pantalla obsoleta la cual será modificada con el sow de fletes y distancia
