### ISSUE TITLE
PRODUCTIVO - Incidencia - Notas de venta y Márgenes (Error en carga de datos)

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#349]
Dentro del modulo Informes: Notas de Venta y Márgenes en las columnas "Costo unit actual" y "Flete unit actual" no se encuentran los datos que corresponden, es decir, no cargan los montos correspondientes, pero si lo hace en el Excel del registro, en el siguiente ejemplo se puede observar de mejor manera: 

Aquí se puede observar en las columnas mencionadas que aparece "#template_costo" y #template_Flete". pero en el Excel aparecen los datos reales.
![image](https://user-images.githubusercontent.com/91085485/164094580-eedd4b54-29f2-4772-9155-2a45d71090eb.png)

Como se puede observar en el archivo descargable si aparecen los datos, **esto ocurre con todas las filas en el registro de Notas de Venta y Márgenes**
![image](https://user-images.githubusercontent.com/91085485/164095228-43e4f6da-2b12-4fcf-bd23-d0a5ad21a0b9.png)

_Esta incidencia se detectó utilizando el perfil Gerente De Ventas_

**Comment by RaisoProg** [comment]
esto no es un error, es una forma de hacerle un parse script directo a un excel
