### ISSUE TITLE
Incidencia - Fletes, Distancias y Tiempos - Tiempos de Traslado Regionales (Error en descargar Excel)

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#352]
Dentro del modulo Fletes, Distancias y Tiempos: Tiempos de Traslado al descargar un archivo Excel este no posee todas las columnas del listado del registro. En la siguiente imagen se puede observar lo mencionado anteriormente: 
 
![image](https://user-images.githubusercontent.com/91085485/164481782-8b6791cd-5710-4881-97c7-18d8c5df6ad0.png)

_Esta incidencia fue detectada utilizando el perfil Administrador_

**Comment by KrishnaMillan** [comment]
![image](https://user-images.githubusercontent.com/45037085/164561380-524f2448-fa2f-426b-b2ef-b9f271646ac3.png)

**Comment by dgroes** [comment]
Corregido por @KrishnaMillan
