### ISSUE TITLE
Incidencia - Fletes, Distancias y Tiempos - Formulas Tarifas Flete (Error en columnas Excel)

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#359]
Dentro del modulo Formulas Tarifas Flete, al descargar el archivo Excel del listado de registros, este posee los siguientes errores:

- Está la columna "Ver", la cual no debería estar.
- La primera columna del Excel, es decir, la columna A no está siendo utilizada, en este caso la tabla de datos debería empezar por esa columna hacia al lado izquierdo

![image](https://user-images.githubusercontent.com/91085485/164507637-2b4a0327-27fb-493a-ab07-9d07e50fe763.png)

_Estas incidencias fueron detectadas utilizando el perfil Administrador_

**Comment by KrishnaMillan** [comment]
![image](https://user-images.githubusercontent.com/45037085/164562100-6e89f4e3-23c8-470a-8794-503506fef4f4.png)

**Comment by dgroes** [comment]
Corregido por @KrishnaMillan
