### ISSUE TITLE
Incidencia - Maestros - Obra y Plantas (Clientes) - Nueva Obra/Planta (Error en numero telefónico)

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#379]
Dentro del modulo Maestros: Obra y Plantas (Clientes), al crear una nueva Obra/Planta, en el formulario "Teléfono/Móvil"  no posee un limite de números pudiendo introducir una gran cantidad de números, además de tener la posibilidad de introducir la letra "e" en dicho numero Telefónico.
![image](https://user-images.githubusercontent.com/91085485/165130470-01d02e32-9593-41c6-8b71-70541b54a378.png)

_Esta incidencia fue detectada utilizando el perfil Administrador._

**Comment by KrishnaMillan** [comment]
Se deja como largo máximo 12, admitiendo el carácter +, en caso de ingresar código de área

**Comment by dgroes** [comment]
Corregido por @KrishnaMillan
