### ISSUE TITLE
Incidencia - Ejecutivo Comercial - Maestros - Regiones (Restricciones del perfil en el Modulo)

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#384]
Utilizando el perfil Ejecutivo Comercial en el modulo de Regiones, se puede tener acceso a todos los permisos del modulo, según el SOW del modulo del sistema, este perfil solo puede visualizar la información y descargarla en formato Excel  
Sistema Actual:
![image](https://user-images.githubusercontent.com/91085485/165149980-071dc414-c71d-48c6-a1b6-72736d72b818.png)

SOW del sistema: 
![image](https://user-images.githubusercontent.com/91085485/165150048-72f09723-7fa9-451e-a09b-efd07f90045c.png)
_Pagina 10 del sow._

**Comment by KrishnaMillan** [comment]
![image](https://user-images.githubusercontent.com/45037085/165410985-da89773e-3ec3-48ad-a41c-d358ba9d3636.png)

**Comment by dgroes** [comment]
Corregido por @KrishnaMillan
