### ISSUE TITLE
Incidencia - Perfil Jefe de Transportes - Dashboard (Asignaciones de Flete pendientes)

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#386]
Dentro del perfil Jefe de Transportes, en la sección dashboard no se encuentra el dashboard "Asignación de Flete Pendientes", en su lugar aun está "Asignaciones de Distancias Pendientes", por lo que aun no es reemplazado según el documento SOW del sistema. 
![image](https://user-images.githubusercontent.com/91085485/165334506-db3b423a-95f9-4618-afef-fd7e082719aa.png)

**Comment by KrishnaMillan** [comment]
![image](https://user-images.githubusercontent.com/45037085/165411216-1987ffd4-89ef-431d-9825-7c9d7e59ad93.png)

**Comment by dgroes** [comment]
Corregido por @KrishnaMillan

**Comment by Ditassara** [comment]
Cambios corroborados en QA y Productivo.
