### ISSUE TITLE
Incidencia - Transportista - Informe Transportista (Menú Lateral)

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#394]
Dentro del perfil Transportista, en el menú la lateral izquierdo, el modulo "Informe Transportista" aparece poco visible, este modulo debe verse como el resto que se encuentra en la plataforma.
![image](https://user-images.githubusercontent.com/91085485/165559511-c283a2c2-767a-4ca6-9297-70f049c932ca.png)

**Comment by KrishnaMillan** [comment]
![image](https://user-images.githubusercontent.com/45037085/165595135-2d605b68-6ed1-4045-b6cb-97f6be27f1dd.png)

**Comment by dgroes** [comment]
Corregido por @KrishnaMillan

**Comment by Ditassara** [comment]
El módulo aparece bien y sin problemas tanto en QA como en Productivo.
