### ISSUE TITLE
Incidencia - Informe Transportista (No funciona Botón "Mostrar Filas")

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#397]
Dentro del modulo Informe Transportista, el botón "Mostrar Filas" no filtra la cantidad de filas mostradas, como si el botón no funcionara, **este error solo aparece en EP Pendientes** 
![image](https://user-images.githubusercontent.com/91085485/165567588-8ec5916a-22ce-4b1e-8b92-60c5edd19afa.png)

**Comment by KrishnaMillan** [comment]
Para el perfil transportista, solo puede descargar en excel
![image](https://user-images.githubusercontent.com/45037085/165600797-9bc88413-7545-4b57-9059-2efad0475ac6.png)

Mientras que para los demás perfiles, se corrigió el error
![image](https://user-images.githubusercontent.com/45037085/165601047-6f44a902-4def-4cbf-a23c-9b23b161803d.png)

**Comment by dgroes** [comment]
Corregido por @KrishnaMillan
