### ISSUE TITLE
Incidencia - Informe Transportista (Filtrar por Transportista)

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#398]
Dentro del modulo Informe Transportista al filtrar por "Transportista" y se selecciona un transportista que no posee registro, luego al volver a uno que si posee registros, estos registros no vuelven a aparecer. 
### Este error ocurre en EP Pendientes y EP Emitidas 
![image](https://user-images.githubusercontent.com/91085485/165570989-3bc9f4a1-677f-497c-a2a9-e701dcaaede6.png)

**Comment by KrishnaMillan** [comment]
![image](https://user-images.githubusercontent.com/45037085/165603724-06abb767-8eca-4f19-a150-5b007b9c6784.png)


![image](https://user-images.githubusercontent.com/45037085/165603613-9816b314-f1d7-4cf5-9069-55050c9ff8bf.png)

**Comment by dgroes** [comment]
Corregido por  @KrishnaMillan

**Comment by sebastianmtralcal** [comment]
Solicitud atendida, se cambian titulos de los excel

**Comment by Ditassara** [comment]
Sigue sin funcionar el filtro. Los nombre de los excel se cambiaron correctamente.

**Comment by Ditassara** [comment]
Cambios confirmados en QA, falta actualización en Producción.

**Comment by Ditassara** [comment]
No se puede corroborar en Productivo ya que no hay datos en tabla.
![image](https://user-images.githubusercontent.com/56659426/185994086-d0c59172-c64a-4114-b6d3-e29214f6d6cd.png)
