### ISSUE TITLE
Incidencia - Informe Transportista (Excel)

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#399]
Dentro del modulo Informe Transportista, falta la opción para descargar el Estado de pago Generado en formato Excel  según el documento SOW del sistema.
SOW, Pagina 35:
![image](https://user-images.githubusercontent.com/91085485/165577103-1c880ded-41b5-46a0-9bb2-8ad80dee3fed.png)

Sistema Actual 
![image](https://user-images.githubusercontent.com/91085485/165577333-681a43b7-84b7-4f32-bd53-62abe3b1a63f.png)

**Comment by KrishnaMillan** [comment]
![image](https://user-images.githubusercontent.com/45037085/165620860-c584efd4-a8f4-4aa7-838a-6e75ee2cc163.png)

**Comment by dgroes** [comment]
Corregido por @KrishnaMillan

**Comment by Ditassara** [comment]
Cambios corroborados en QA y Productivo.
