### ISSUE TITLE
Incidencia - Informe Transportista - Estado de Pago (Botón "Imprimir")

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#400]
Dentro del modulo Informe Transportista, en EP Emitidos, al abrir el modal de Estado de Pago de algún ID, este no se puede descargar, el botón "Imprimir" no funciona.
![image](https://user-images.githubusercontent.com/91085485/165579774-8c8fd422-d242-4d78-9c8d-b386a7c573d4.png)

**Comment by KrishnaMillan** [comment]
![image](https://user-images.githubusercontent.com/45037085/165633198-2d61235e-942b-4c4d-9c11-0ae5d0cefae0.png)

**Comment by dgroes** [comment]
Corregido por @KrishnaMillan

**Comment by Ditassara** [comment]
Funciona sin problemas en QA, en productivo no hay datos para corroborar.
