### ISSUE TITLE
Incidencia - Perfil Jefe de Transporte - Informe Transportista (Columna innecesaria)

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#401]
Dentro del modulo Informe Transportista el perfil Jefe de Transporte puede visualizar la columna de los "Check Box", esta columna debe ser eliminada de este perfil.
SOW Pagina 37:
![image](https://user-images.githubusercontent.com/91085485/165589063-9d475664-d3a8-4661-acbe-eba66e4c636b.png)

Sistema Actual:
![image](https://user-images.githubusercontent.com/91085485/165588989-b81bdf0c-52f1-4eae-bf5c-728d1c041035.png)

**Comment by KrishnaMillan** [comment]
![image](https://user-images.githubusercontent.com/45037085/165605977-fbaef665-e045-4920-abc7-1db94610b7cd.png)

**Comment by dgroes** [comment]
Corregido por @KrishnaMillan

**Comment by Ditassara** [comment]
En ambiente QA y productivo sigue apareciendo la columna, no aparecen los "Check Box" en los datos, pero la columna si.

QA
![image](https://user-images.githubusercontent.com/56659426/182865876-29235b64-4561-48d6-ae4e-0d834393d27d.png)
Productivo
![image](https://user-images.githubusercontent.com/56659426/182866010-cc992257-a051-4c81-aaf3-8ad7950641a3.png)

**Comment by sebastianmtralcal** [comment]
Solicitud atendida

**Comment by Ditassara** [comment]
Cambio confirmado en QA, falta actualización en Producción.
