### ISSUE TITLE
Incidencia - Perfil Ejecutivo Administrativo - Informe transportista (No está el Modulo)

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#402]
Dentro del Ejecutivo Administrativo no se puede ver el modulo Informe Transportista, según en el SOW este si debe estar dentro de este perfil.   
![image](https://user-images.githubusercontent.com/91085485/165599009-8cf36449-d077-4a7c-ab6f-824f09cdf468.png)

**Comment by KrishnaMillan** [comment]
![image](https://user-images.githubusercontent.com/45037085/165634107-1e6e60bd-1fb3-443c-b4c5-7dddffcb337b.png)

**Comment by dgroes** [comment]
Corregido por @KrishnaMillan
