### ISSUE TITLE
Incidencia - Perfil Ejecutivo de Crédito - Informe Transportista (No está el modulo)

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#403]
Dentro del Ejecutivo de Crédito no se puede ver el modulo Informe Transportista, según en el SOW este si debe estar dentro de este perfil.
![image](https://user-images.githubusercontent.com/91085485/165601080-5aab17b5-870f-4add-87a5-8e10e71f3372.png)
Pagina 37 del SOW

**Comment by KrishnaMillan** [comment]
![image](https://user-images.githubusercontent.com/45037085/165634494-19badbe8-32f1-4a1a-9c73-a7c878bff4d3.png)

**Comment by dgroes** [comment]
Corregido por @KrishnaMillan
