### ISSUE TITLE
Incidencia - Fletes, Distancias y Tiempos - Datos de Fletes a Obras y Plantas (Botón Mostrar Filas)

### ISSUE THREAD

**Issue by dgroes** [rhasbun1/qlnow#407]
Dentro del modulo Datos de Fletes a Obras y Plantas, no se encuentra el botón "mostrar filas", Según las pantallas creadas en el SOW, este botón debe estar presente en este modulo.
SOW, Pagina 27:
![image](https://user-images.githubusercontent.com/91085485/165835981-071199b6-2678-45bd-a75d-4e6517155c6f.png)

**Comment by KrishnaMillan** [comment]
![image](https://user-images.githubusercontent.com/45037085/165849327-4d81bd2b-ae63-4fae-ba89-a6c86e5268f7.png)

**Comment by dgroes** [comment]
Corregido por @KrishnaMillan
