### ISSUE TITLE
QA R-242

### ISSUE THREAD

**Issue by nataliabastias** [rhasbun1/qlnow#415]
Pedido en formato otro mas de 1 producto
al asignar y/o sube guía a uno de los productos no desaparece el botón de "Cerrar Pedido"

![image](https://user-images.githubusercontent.com/91262410/166293505-6ea239aa-0b85-4261-a7ae-fd8ecb7ab409.png)

**Comment by KrishnaMillan** [comment]
![image](https://user-images.githubusercontent.com/45037085/166833448-f1be3757-e27c-4f8c-8e49-c7eceef3ac4b.png)
![image](https://user-images.githubusercontent.com/45037085/166833469-a3d5dccf-d478-4711-9aa5-1dd4a13d37d6.png)
