### ISSUE TITLE
Fórmulas Tarifa Fletes (Gerente Comercial)

### ISSUE THREAD

**Issue by cbastiasv** [rhasbun1/qlnow#416]
Se encuentra habilitado el botón para guardar los cambios de las fórmulas. El Gerente comercial solo puede ver los datos.

<img width="661" alt="image" src="https://user-images.githubusercontent.com/91262348/166474239-424ebe29-7fa2-4dcc-9317-63f96fdc5737.png">

**Comment by KrishnaMillan** [comment]
![image](https://user-images.githubusercontent.com/45037085/166729123-d21fdf2c-0526-4e71-811d-418b0f0fe55a.png)
