### ISSUE TITLE
Obras y Plantas (Clientes)

### ISSUE THREAD

**Issue by cbastiasv** [rhasbun1/qlnow#418]
La lista desplegable Región debe mostrar el ID de la región y el nombre de esta separados por un guion (ID - Nombre de la Región). 

<img width="665" alt="image" src="https://user-images.githubusercontent.com/91262348/166492433-18deea46-58dc-4e17-842e-8b3e4aae8e0b.png">

**Comment by KrishnaMillan** [comment]
![image](https://user-images.githubusercontent.com/45037085/166745571-6e20532d-553b-4f2a-9d8f-be579e72331d.png)
