### ISSUE TITLE
Tiempos de Traslado Regionales (Ejecutivo Comercial)

### ISSUE THREAD

**Issue by cbastiasv** [rhasbun1/qlnow#419]
El botón guardar está habilitado. El ejecutivo comercial solo puede ver y descargar el listado

<img width="467" alt="image" src="https://user-images.githubusercontent.com/91262348/166494808-e2c2fcd2-f597-4c59-a975-30a7b624faea.png">

**Comment by KrishnaMillan** [comment]
![image](https://user-images.githubusercontent.com/45037085/166746131-abf29f61-01bb-42d3-bee0-67c4053ef11b.png)
