### ISSUE TITLE
Fórmula Tarifas Fletes (Ejecutivo Comercial Plus y Gerente de Ventas)

### ISSUE THREAD

**Issue by cbastiasv** [rhasbun1/qlnow#420]
Estos perfiles solo puede ver y descargar la información.

<img width="619" alt="image" src="https://user-images.githubusercontent.com/91262348/166497252-5538db34-3ea2-4689-9619-d33db7b54b64.png">

<img width="668" alt="image" src="https://user-images.githubusercontent.com/91262348/166497747-494612cc-6536-453e-8cc6-5bbbc2b16d74.png">

**Comment by KrishnaMillan** [comment]
![image](https://user-images.githubusercontent.com/45037085/166803900-de160041-7c50-46e5-927c-8f182d95fee6.png)
