### ISSUE TITLE
Dashboard - Asignaciones de distancias pendientes

### ISSUE THREAD

**Issue by cbastiasv** [rhasbun1/qlnow#421]
La tabla tiene una columna distancia pero contiene solo datos a los cuales no se les ha ingresado distancia por lo que no tiene sentido que este en la tabla. Nunca tendrá datos.

<img width="440" alt="image" src="https://user-images.githubusercontent.com/91262348/166686240-3da0c382-9244-40c0-a79d-12561029634d.png">

**Comment by KrishnaMillan** [comment]
![image](https://user-images.githubusercontent.com/45037085/166804770-36ccba92-f11e-46af-a29a-c63526023039.png)
