### ISSUE TITLE
Programación de Pedidos (Jefe de Planta (adm. directa)

### ISSUE THREAD

**Issue by cbastiasv** [rhasbun1/qlnow#426]
Al intentar ingresar a un pedido, el sistema arroja error

<img width="452" alt="image" src="https://user-images.githubusercontent.com/91262348/166935813-9a44c3d7-0d75-4d9a-8655-ae761ade4f40.png">

<img width="713" alt="image" src="https://user-images.githubusercontent.com/91262348/166935901-e36a5a13-8a24-48e3-bee1-f466bf978158.png">

**Comment by Ditassara** [comment]
Funciona sin problemas en ambiente QA y Productivo.
