### ISSUE TITLE
Informe Transportista

### ISSUE THREAD

**Issue by cbastiasv** [rhasbun1/qlnow#429]
Fecha en formato incorrecto

<img width="700" alt="image" src="https://user-images.githubusercontent.com/91262348/167019948-93ae1c24-1163-48d0-8190-26fdc75e9c87.png">

**Comment by KrishnaMillan** [comment]
![image](https://user-images.githubusercontent.com/45037085/167155553-017f2dbd-a9f3-4384-b282-5843d586d96a.png)

**Comment by Ditassara** [comment]
Cambios corroborados en ambiente QA, en producción no hay datos para confirmar.

QA
![image](https://user-images.githubusercontent.com/56659426/182716094-6e204c7d-2227-4e10-839a-9972667cb6f1.png)
Productivo
![image](https://user-images.githubusercontent.com/56659426/182716151-257a230e-86d3-433d-b9ab-7e5202132cf9.png)
