### ISSUE TITLE
583 - Dashboard Pedidos en Proceso (Cliente Full)

### ISSUE THREAD

**Issue by cbastiasv** [rhasbun1/qlnow#431]
El número de pedidos parece no corresponder con el listado de pedidos que se muestra al presionar en el.  El listado muestra cada producto del pedido pero al agruparlos da un numero mayor que el mostrado en el dashboard

<img width="279" alt="image" src="https://user-images.githubusercontent.com/91262348/167219648-856e7cfe-99f8-4522-bbc9-367f41288551.png">

<img width="472" alt="image" src="https://user-images.githubusercontent.com/91262348/167219879-ebd4d093-48ad-43e7-a234-c04b7c9db29b.png">

**Comment by KrishnaMillan** [comment]
Se cuentan los detalle pedidos que posean un ID distinto

![image](https://user-images.githubusercontent.com/45037085/167482267-b3080bee-11b2-42b9-8ad0-1496ad89dd78.png)

**Comment by Ditassara** [comment]
Los cambios no se reflejan en QA y Productivo, sigue mostrando un número distinto al de la tabla.

QA
![image](https://user-images.githubusercontent.com/56659426/182708603-74787425-88bf-4969-aa7a-b284557bd38e.png)
![image](https://user-images.githubusercontent.com/56659426/182708693-0093de35-a1e8-4439-9742-2e803da2fd35.png)
Productivo
![image](https://user-images.githubusercontent.com/56659426/182708759-26a2bdd5-af77-4811-b0c8-28b146fda4a9.png)
![image](https://user-images.githubusercontent.com/56659426/182708811-ac2e138b-2d04-482b-96bf-b7f6520c3ef0.png)
