### ISSUE TITLE
580 - Maestro Clientes

### ISSUE THREAD

**Issue by cbastiasv** [rhasbun1/qlnow#432]
Algunos Clientes, en la columna Cód. Softland, aparecen sin datos pero al abrir el formulario de modificación aparecen datos en el campo Cód. Softland (CS) (Al intentar guardar los datos aparece un mensaje señalando que el código ingresado no existe en contabilidad.)

<img width="1106" alt="image" src="https://user-images.githubusercontent.com/91262348/167220521-87b0703d-6b53-44ed-bead-266d90a9ef83.png">

<img width="436" alt="image" src="https://user-images.githubusercontent.com/91262348/167220542-2f09210c-d63c-4f23-a03a-358f5125684f.png">

**Comment by Ditassara** [comment]
Cambios corroborados en ambiente QA y Productivo.

![image](https://user-images.githubusercontent.com/56659426/182713713-222cf902-8f96-4c77-9a25-cbfac6b9a544.png)
![image](https://user-images.githubusercontent.com/56659426/182713749-ec73dc94-6e07-4303-aebd-c06cc4d1116f.png)
