### ISSUE TITLE
576 - Dashboard Pedidos Atrasados

### ISSUE THREAD

**Issue by cbastiasv** [rhasbun1/qlnow#433]
Cuenta productos. Debe contar pedidos

<img width="278" alt="image" src="https://user-images.githubusercontent.com/91262348/167221300-c2e05838-2320-483d-b668-1e0ad1c44da0.png">

<img width="545" alt="image" src="https://user-images.githubusercontent.com/91262348/167221396-b0ad05c5-c380-48d9-adcb-d11fbac13ab6.png">

**Comment by KrishnaMillan** [comment]
Se cuentan pedidos
![image](https://user-images.githubusercontent.com/45037085/167472435-556921d3-ba4d-454d-bf71-4db035749e05.png)

Se muestran detalle de pedidos
![image](https://user-images.githubusercontent.com/45037085/167472514-bf2f5d56-a6cd-4458-bb90-179430f5909b.png)

**Comment by Ditassara** [comment]
Cambios corroborados en Producción, en ambiente QA sigue mostrando una cantidad distinta.

QA
![image](https://user-images.githubusercontent.com/56659426/182717509-a2487a47-284b-4867-abd6-4feb9739ca11.png)
![image](https://user-images.githubusercontent.com/56659426/182717555-7122e750-f622-49f4-8652-f1ca16bcdef5.png)
Productivo
![image](https://user-images.githubusercontent.com/56659426/182717608-5f4b84ba-feab-479e-86fc-98a0dc984618.png)
![image](https://user-images.githubusercontent.com/56659426/182717646-d2758564-8b5b-4946-8dc7-2aaad9be3f5e.png)
