### ISSUE TITLE
576 - Pedidos pendientes de aprobación de crédito

### ISSUE THREAD

**Issue by cbastiasv** [rhasbun1/qlnow#434]
El dashboard muestra 380, el registro de la tabla 397 (pero esta cuenta es por producto y el dashboard de be mostrar por pedido) y según mi cuenta hay 292 pedidos

<img width="272" alt="image" src="https://user-images.githubusercontent.com/91262348/167222128-77531e62-4434-4ee0-a02b-5f2c6be204b8.png">

<img width="401" alt="image" src="https://user-images.githubusercontent.com/91262348/167222160-c9d5cfa9-80b7-4b98-b838-724625d6560f.png">

**Comment by KrishnaMillan** [comment]
Se cuentan los id de pedido que sean distintos y que tengan estado pendiente de VB Crédito
![image](https://user-images.githubusercontent.com/45037085/167475476-d2a92223-7ef9-4e7e-b85f-e9d008ac8905.png)

**Comment by cbastiasv** [comment]
Descargando y contando los pedidos de la tabla del dashboard me da un total de 308. Pero en pedidos en proceso, descargando solo los pedidos pendientes de vb crédito da 369. Por algún motivo una tabla tiene más pedidos que la otra, ¿datos basura?

308 pedidos aquí
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/91262348/167642726-95b7f5be-577b-42c5-a621-ae0ddb2f22b1.png">

369 pedidos aquí
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/91262348/167642916-746a4601-8606-4966-bbb0-5b1a14d628c1.png">

**Comment by Russal-O** [comment]
QA CLIENTE FULL:
No coincide
![imagen](https://user-images.githubusercontent.com/83325414/182681188-65662910-cd4a-4474-8722-9d2ad5632748.png)
![imagen](https://user-images.githubusercontent.com/83325414/182681319-32c1006f-a84d-445a-a890-d9d3d7b337cd.png)
![imagen](https://user-images.githubusercontent.com/83325414/182681381-db71a432-da55-405e-99f7-597c998eddb6.png)

PRODUCTIVIDAD CLIENTE FULL:
![imagen](https://user-images.githubusercontent.com/83325414/182681657-dfcc4678-16f3-4d1b-95ce-46541d4ed724.png)
![imagen](https://user-images.githubusercontent.com/83325414/182681714-23b50ca1-4d2f-42e3-b2af-97863ee1e09f.png)
NO PERMITE FILTRAR PENDIENTE VB CRÉDITO: ![imagen](https://user-images.githubusercontent.com/83325414/182681742-d4d74a38-cf59-49b4-a1fb-f7f30914c6f6.png)
