### ISSUE TITLE
576 - Pedidos sin Transporte Asignado

### ISSUE THREAD

**Issue by cbastiasv** [rhasbun1/qlnow#435]
Cuenta productos y debe contar pedido

<img width="285" alt="image" src="https://user-images.githubusercontent.com/91262348/167222519-2267be29-faea-4ccf-873a-4e81afd13000.png">

<img width="484" alt="image" src="https://user-images.githubusercontent.com/91262348/167222555-f0cb0b28-bc9c-4b42-a716-3e6b1e9842ff.png">

**Comment by KrishnaMillan** [comment]
![image](https://user-images.githubusercontent.com/45037085/167484119-ddfca26c-ced6-4cff-b8a5-bfb19207a1a5.png)
