### ISSUE TITLE
R569 QA PRODUCTIVO

### ISSUE THREAD

**Issue by nataliabastias** [rhasbun1/qlnow#475]
implementado pero al costado derecho de Fecha carga y debe ser " la columna "plazo", mostrar a la derecha de "Fecha de Entrega""

**Comment by KrishnaMillan** [comment]
![image](https://user-images.githubusercontent.com/45037085/172893592-8ef69e3e-d84f-40e6-ae05-acaca9c7d1ab.png)

**Comment by nataliabastias** [comment]
OK QA ambiente PRODUCTIVO
