### ISSUE TITLE
INFORME TRANSPORTISTA

### ISSUE THREAD

**Issue by nataliabastias** [rhasbun1/qlnow#477]
las columnas están fijas no es posible ver la columna total

![image](https://user-images.githubusercontent.com/91262410/172423103-e5c08061-b082-4379-ba3c-ea195c01ed13.png)

**Comment by nataliabastias** [comment]
Pendiente: la fila del encabezado esta fija e independiente de las filas con el contenido, por lo que al intentar visualizar el contenido de la tabla no visible (derecha) solo se visualiza el contenido pero no la primera fila con los encabezados.

![image](https://user-images.githubusercontent.com/91262410/173089889-0317813b-eac7-4a97-bc3f-d5b3b931b4f0.png)

**Comment by nataliabastias** [comment]
QA ambiente QA OK

**Comment by nataliabastias** [comment]
QA Productivo OK

**Comment by Ditassara** [comment]
Es posible ver la columna, pero se pierde el formato de la tabla, en ambiente QA y en Productivo.


https://user-images.githubusercontent.com/56659426/182711765-51da93ea-d609-4bbd-89e2-1cee6c0cddc8.mp4

**Comment by sebastianmtralcal** [comment]
Solicitud atendida, se cuadra tabla

**Comment by Ditassara** [comment]
Cambios confirmados en QA, falta actualización en Productivo.
