### ISSUE TITLE
R585 - Cliente Full, Gerente Comercial, Gerente Ventas - Modificar Pedidos

### ISSUE THREAD

**Issue by cbastiasv** [rhasbun1/qlnow#487]
En pedidos granel/mixtos es posible editar la forma de Entrega de uno de ellos. Los dos productos de los pedidos mixtos deben tener la misma forma de entrega siempre.

<img width="713" alt="image" src="https://user-images.githubusercontent.com/91262348/173850723-1d0cfe18-7df3-44e3-9925-6d768def89c3.png">
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/91262348/173851013-3f34a1e8-faca-432a-abd6-1d2a21df0a0a.png">

**Comment by KrishnaMillan** [comment]
Perfil no cliente:
![image](https://user-images.githubusercontent.com/45037085/175417838-2c64b249-c684-49bf-b126-57d07022ed6a.png)


Perfil Cliente:
![image](https://user-images.githubusercontent.com/45037085/175418274-6feedc73-39dd-4873-a6aa-59b2d207512f.png)
