### ISSUE TITLE
R586 - Cliente Full - Crear Pedido Mixto

### ISSUE THREAD

**Issue by cbastiasv** [rhasbun1/qlnow#488]
Al crear un pedido mixto a partir de una nota de ventas con productos de diferentes plantas de origen, el sistema cambia las plantas de los productos ingresados. No se debe dejar crear pedidos mixtos con diferentes plantas de origen para los usuarios clientes full. Alertar al usuario que intenta crear el pedido con el siguiente mensaje: Está seleccionando dos productos que tienen asignados una planta de origen distinta, por lo que no puede crearse este pedido. Cambie los productos o contacte a su ejecutivo comercial para solicitarle ayuda

<img width="1194" alt="image" src="https://user-images.githubusercontent.com/91262348/173862577-d1f4c56b-4ccd-446f-81ee-adec5b6274e9.png">
<img width="1123" alt="image" src="https://user-images.githubusercontent.com/91262348/173862727-3e780d09-d7b5-427d-a8fa-ba8dfda80030.png">

**Comment by KrishnaMillan** [comment]
![image](https://user-images.githubusercontent.com/45037085/175387364-81ef8cac-9b61-44a3-a57f-ebe64f66072b.png)
![image](https://user-images.githubusercontent.com/45037085/175387412-482d0fdc-808f-444e-a58f-cc965c0904d1.png)
