### ISSUE TITLE
R590 - Cliente Full - Suspender Pedido

### ISSUE THREAD

**Issue by cbastiasv** [rhasbun1/qlnow#489]
Aparece, en un pedido ya suspendido, el botón Suspender. 
El pedido fue suspendido cuando se encontraba en estado Aprobado y por un usuario Gerente Comercial.

<img width="409" alt="image" src="https://user-images.githubusercontent.com/91262348/173887313-351b1c43-0099-4ae2-b48e-3fcb74c56d6f.png">

**Comment by Russal-O** [comment]
Corregido: ya no aparece botón suspender para pedido suspendido.
![imagen](https://user-images.githubusercontent.com/83325414/182691858-e7bb7a9b-090d-489e-9977-f18358d10bd1.png)

**Comment by Russal-O** [comment]
Alcance en la segunda indicación:
![imagen](https://user-images.githubusercontent.com/83325414/182692235-c19e9e74-e125-4873-adad-4c7995c5177f.png)
