### ISSUE TITLE
R591 - Perfil Cliente - Pedidos en Proceso

### ISSUE THREAD

**Issue by cbastiasv** [rhasbun1/qlnow#490]
No aparecen los iconos que muestran que ha un pedido se le ha asignado el transportista y el horario de carga

<img width="379" alt="image" src="https://user-images.githubusercontent.com/91262348/173889942-2d2ad348-f822-4d13-8b92-dfbdf20f7347.png">

<img width="265" alt="image" src="https://user-images.githubusercontent.com/91262348/173890030-89fe53c5-15d5-496f-8755-7e7cde9691b9.png">

**Comment by Russal-O** [comment]
QA Y PRODUCTIVO CON ÍCONOS
![imagen](https://user-images.githubusercontent.com/83325414/182691273-58b434e9-9e1d-4ee1-8bbc-486947af45e6.png)
![imagen](https://user-images.githubusercontent.com/83325414/182691311-06e1d2cc-a930-463e-a9a7-7a7c18cc1d01.png)
