### ISSUE TITLE
R592 - Editar/Crear Producto

### ISSUE THREAD

**Issue by cbastiasv** [rhasbun1/qlnow#491]
Si se entra a editar un producto y luego se intenta crear uno, el formulario mantiene el precio del producto que se editó en el formulario de creación de producto

<img width="437" alt="image" src="https://user-images.githubusercontent.com/91262348/173893897-7b9a0812-9b85-4b3e-a493-c8036bf6acb4.png">
<img width="436" alt="image" src="https://user-images.githubusercontent.com/91262348/173893976-2f6273aa-3bf5-46a7-b512-e3f6b5ea906d.png">

**Comment by KrishnaMillan** [comment]
![image](https://user-images.githubusercontent.com/45037085/175368624-1a367187-58a0-4fbc-80d3-95b6553d7879.png)
![image](https://user-images.githubusercontent.com/45037085/175368692-949f3902-1621-4751-a104-1e92fa041bf4.png)
