### ISSUE TITLE
Distancias Pendientes - Jefe de Transportes

### ISSUE THREAD

**Issue by cbastiasv** [rhasbun1/qlnow#497]
El check ver solo distancias pendientes no funciona al entrar al listado desde Distancias Pendientes.

<img width="551" alt="image" src="https://user-images.githubusercontent.com/91262348/175369357-017d8036-3fb0-4d9d-950d-889bb790a5f0.png">

**Comment by KrishnaMillan** [comment]
En este módulo, el sistema muestra todas aquellas distancias que no hayan sido definidas, al igual que el check, por lo que ambos muestran lo mismo. Sería mejor quitarlo de este modulo y dejarlo solo en módulo "Datos de Fletes a Obras y Plantas"?

**Comment by cbastiasv** [comment]
Sí, lo mejor es quitar el check

**Comment by KrishnaMillan** [comment]
![image](https://user-images.githubusercontent.com/45037085/176273941-e3461e61-9d83-450d-ace2-609c607b269e.png)

**Comment by Ditassara** [comment]
Cambios corroborados en QA y producción.

QA
![image](https://user-images.githubusercontent.com/56659426/182696734-f6c19e7c-e1e4-4732-bbdb-24c9487e5245.png)
Producción
![image](https://user-images.githubusercontent.com/56659426/182696863-0216d989-2515-4402-8ca5-96951353ecfb.png)
