### ISSUE TITLE
Generar Estado de Pago - Transportista

### ISSUE THREAD

**Issue by cbastiasv** [rhasbun1/qlnow#500]
No se puede generar un estado de pago. La consola muestra un error

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/91262348/175384913-cee820b1-0949-41bb-a509-674ab0697940.png">

**Comment by KrishnaMillan** [comment]
![image](https://user-images.githubusercontent.com/45037085/175572491-79f75cbc-4d92-4f6b-95cf-303f82289788.png)

**Comment by Ditassara** [comment]
No es posible corroborar en el productivo ya que no existen datos en la tabla; la tabla pierde el formato.


https://user-images.githubusercontent.com/56659426/182689264-0a6d76fd-89f5-4a6c-9ea8-5891133e6605.mp4


En el ambiente de qa funciona sin problemas, pero se pierde el formato de la tabla igualmente.

**Comment by sebastianmtralcal** [comment]
Solicitud atendida, ya no se pierde el formato de la tabla

**Comment by Ditassara** [comment]
La tabla ya no pierde el formato, pero los datos no van con las columnas.

**Comment by sebastianmtralcal** [comment]
Solicitud atendiuda, Se termina de cuadrar la tabla, faltaba la primera columna

**Comment by Ditassara** [comment]
Cambios confirmados en QA, falta actualización en Producción.
