### ISSUE TITLE
Informe Transportista - Usuarios QLSA

### ISSUE THREAD

**Issue by cbastiasv** [rhasbun1/qlnow#501]
Según el documento, el acceso al informe transportista se encontrará dentro de la sección informes (página 37)

<img width="235" alt="image" src="https://user-images.githubusercontent.com/91262348/175385895-c449441c-6e66-4648-b8c6-72161025fa12.png">

**Comment by KrishnaMillan** [comment]
Usuarios qlsa
![image](https://user-images.githubusercontent.com/45037085/175563130-e2282c80-7a18-432a-970c-08a9afb8f035.png)

Transportista
![image](https://user-images.githubusercontent.com/45037085/175563372-403cda5e-a3e0-4a28-9d50-3ef2d231c149.png)

**Comment by Ditassara** [comment]
Cambios confirmados en ambiente qa y en producción.
