### ISSUE TITLE
Generar Estado de Pago - Perfiles QLSA

### ISSUE THREAD

**Issue by cbastiasv** [rhasbun1/qlnow#502]
Según el documento, los perfiles Jefe de Transporte pueden generar estados de pago o incorporar un viaje (ep. pendiente) a un ep. emitido. (Pensando, sobre todo, en empresas de transporte que no tienen acceso a qlnow) (página 37)

**Comment by KrishnaMillan** [comment]
![image](https://user-images.githubusercontent.com/45037085/175697813-ce36d155-8d60-4b83-bafd-676ff9a03aa2.png)
![image](https://user-images.githubusercontent.com/45037085/175697858-0ab71303-1b28-4e7a-b914-118ae3c3ae48.png)
![image](https://user-images.githubusercontent.com/45037085/175697882-61292b8e-170a-4e8e-8245-c4da71188de0.png)
