### ISSUE TITLE
Incidencia en tablas cuando pedido se encuentra en estado "suspendido"

### ISSUE THREAD

**Issue by Russal-O** [rhasbun1/qlnow#508]
Al presionar los títulos de las columnas, estas cambian de color y no permiten ver el texto en las casillas.

https://user-images.githubusercontent.com/83325414/182704222-f52aa14a-7290-4afc-850c-48d5f864141b.mp4

**Comment by Russal-O** [comment]
![imagen](https://user-images.githubusercontent.com/83325414/182681742-d4d74a38-cf59-49b4-a1fb-f7f30914c6f6.png)

**Comment by Ditassara** [comment]
Cambios confirmados en QA, falta actualización en Productivo.

**Comment by Ditassara** [comment]
Cambios confirmados en Producción.
