### ISSUE TITLE
Ortografía

### ISSUE THREAD

**Issue by nataliabastias** [rhasbun1/qlnow#517]
Error en mensaje de validación a momento de crear pedido , Cambiar Agrege por Agregue 

![image](https://user-images.githubusercontent.com/91262410/184411490-6d361037-f76e-4683-9d09-790d7befa9a2.png)

**Comment by sebastianmtralcal** [comment]
Se corrige palabra agrege por agregue

**Comment by nataliabastias** [comment]
QA Ok ambiente QA
