### ISSUE TITLE
N°225 Crear pedido

### ISSUE THREAD

**Issue by nataliabastias** [rhasbun1/qlnow#518]
Hallazgo:
Al crea pedidos consecutivos el sistema muestra la planta ingresada en el pedido anterior y no el por defecto que se obtiene desde la nota de venta.

Ejemplo según nota de venta :Planta  Viña, el pedido anterior se cambio la planta por "Viña (DASA)" y esta planta es la que se visualiza al seleccionar que se desea continuar generando pedidos a la misma nota de venta.

http://172.16.0.5/qlnow/gestionarpedido/3632

![image](https://user-images.githubusercontent.com/91262410/184412382-e94e1f86-9794-4802-9a23-0762d5aa5a5c.png)

Requerimiento:
11/07/2022: No se están restableciendo correctamente los valores predefinidos de Planta de Origen y Forma de Entrega. Ejemplo NV 4836. Si cambio planta de origen y/o forma de entrega prestablecido de uno o más productos, al crear un segundo y tercer predefinido consecutivo no se devuelve a los valores predefinidos de cada producto. NUEVAMENTE SE REPITE ESTA OBSERVACIÓN!!

**Comment by nataliabastias** [comment]
Ambiente QA pendiente

**Comment by sebastianmtralcal** [comment]
Problema resuelto

**Comment by nataliabastias** [comment]
OK ambiente PRODUCTIVO probado en el perfil gerente comercial
