### ISSUE TITLE
Nº549 Estado de Pedidos

### ISSUE THREAD

**Issue by nataliabastias** [rhasbun1/qlnow#519]
Requerimiento:
La mayoría de los pedidos está quedando como "despachado parcial" cuando se pasan al histórico, aun cuando tienen un solo producto (error). Corregir, ya que los despachos parciales solo aplican para pedidos con varios productos en los cuales solo se despachan algunos y no todos, y en esa situación se pasan al histórico.

![image](https://user-images.githubusercontent.com/91262410/184413689-39509d3a-87ea-431b-9a4e-de2625ab03a1.png)

**Comment by sebastianmtralcal** [comment]
Esto se explicó indicando que quedaron tickets anteriores con ese problema pero para futuros tickets ya no vuelve a pasar
