### ISSUE TITLE
Nº545 Histórico de Pedidos Despachados

### ISSUE THREAD

**Issue by nataliabastias** [rhasbun1/qlnow#520]
Se duplican guías para distintos pedidos.

![image](https://user-images.githubusercontent.com/91262410/184415580-2e259a3d-fe61-4e71-a242-8d29cf5b7b52.png)

![image](https://user-images.githubusercontent.com/91262410/184415912-ce85efce-e3b8-4664-a6a2-a7d6c4d3ee73.png)

![image](https://user-images.githubusercontent.com/91262410/184415840-1e70ad8e-0ed6-43cc-8dac-069d4e4389d4.png)

![image](https://user-images.githubusercontent.com/91262410/184415976-5ee17783-7a00-4e81-b350-f2ba4034b7d2.png)

![image](https://user-images.githubusercontent.com/91262410/184416079-dfb41215-45e3-4da6-8aad-6dd3d505c32f.png)

![image](https://user-images.githubusercontent.com/91262410/184416159-22014853-b5f4-4ccb-8e8e-77e517055177.png)

**Comment by sebastianmtralcal** [comment]
Se conversa en reunion de la mañana quedando como tarea completada
