### ISSUE TITLE
Ver siguiente hoja.

### ISSUE THREAD

**Issue by nataliabastias** [rhasbun1/qlnow#522]
Perfil Cliente limitado y full pedidos en proceso se visualiza de forma extraña los botones de cambiar hoja

![image](https://user-images.githubusercontent.com/91262410/184937208-f07c51ca-9372-4bf7-8797-3b492e422266.png)

**Comment by sebastianmtralcal** [comment]
![image](https://user-images.githubusercontent.com/86976515/184963682-db90826b-670e-4399-8a8d-eded372f83ab.png)
 
problema resuelto

**Comment by nataliabastias** [comment]
Se debería ver como las ostras pantallas 
como se visualiza : 
![image](https://user-images.githubusercontent.com/91262410/185182427-b1c89887-5d49-4b18-af22-a8ed722aed14.png)

Como se debería visualizar:
![image](https://user-images.githubusercontent.com/91262410/185182705-759de56e-b838-473a-ac0e-44fffe007635.png)

**Comment by nataliabastias** [comment]
Pendiente ambiente QA

**Comment by sebastianmtralcal** [comment]
![image](https://user-images.githubusercontent.com/86976515/185676655-bbdaee5a-65bd-41d5-aec4-4db4ba739560.png)

problema resuelto el causante era el llamado de bJQueryUI

**Comment by Ditassara** [comment]
Cambios confirmados en QA y Productivo.
