### ISSUE TITLE
Permite letras en cantidad al momento de modificar.

### ISSUE THREAD

**Issue by nataliabastias** [rhasbun1/qlnow#524]
![image](https://user-images.githubusercontent.com/91262410/185156291-538c8bfb-eea8-4c76-94fc-45c66ccc4bb3.png)

**Comment by sebastianmtralcal** [comment]
Se limita a 10 caracteres y solo permite números

**Comment by nataliabastias** [comment]
Pendiente ambiente QA solo ocurre con el primer producto
![image](https://user-images.githubusercontent.com/91262410/185659027-1454a55e-67ba-4eba-a204-e58f42c57505.png)

**Comment by sebastianmtralcal** [comment]
Problema resuelto, se arregla el problema de escribir letras

**Comment by Ditassara** [comment]
Cambios confirmados en QA y Productivo.
