### ISSUE TITLE
Validación:

### ISSUE THREAD

**Issue by nataliabastias** [rhasbun1/qlnow#526]
Pedidos Formato: Otros 
Forma de Entrega : En Obra
Con 1 y más productos
Fuera y Dentro de plazo.

Hallazgo: Aparece el validador de Flete falso

Prueba Pedidos: 10716 - 10717 - 10717 - 10718

http://172.16.0.5/qlnow/editarPedido/10717

![image](https://user-images.githubusercontent.com/91262410/185472203-7beb9e87-448f-4974-803b-ce335abeeb19.png)

**Comment by sebastianmtralcal** [comment]
Problema solucionado, se hizo pruebas en cada uno de los casos , Prueba Pedidos: 10716 - 10717 - 10717 - 10718

![image](https://user-images.githubusercontent.com/86976515/185646890-0d75505e-75c1-43ae-8b83-cbc3efe05092.png)

**Comment by nataliabastias** [comment]
OK QA
