### ISSUE TITLE
Nº603 Maestro Clientes - Distribuir el listado en varias páginas, como ocurre con la mayoría del listado. Ideal 12 registros por página.

### ISSUE THREAD

**Issue by Ditassara** [rhasbun1/qlnow#534]
Actualmente está mostrando todas las filas por defecto, solución cambiar a 12 registros por defecto.

**Comment by sebastianmtralcal** [comment]
![image](https://user-images.githubusercontent.com/86976515/186272615-ca80bfbe-6984-47a2-b29d-3c156d986319.png)


Solicitud atendida, Se pone por defecto en 12 filas

**Comment by Ditassara** [comment]
Cambios confirmados en ambiente QA.
