### ISSUE TITLE
Requerimiento 516 Validador Pedido fuera de plazo

### ISSUE THREAD

**Issue by nataliabastias** [rhasbun1/qlnow#538]
QA PRODUCTIVO
el Calculo que realiza para definir si el pedido esta o no fuera de plazo, es distinta al momento de crear y editar el pedido.

**Comment by nataliabastias** [comment]
[SOW Estado Pedidos 2020-09-22 (NB) (ultimo).docx](https://github.com/rhasbun1/qlnow/files/9410266/SOW.Estado.Pedidos.2020-09-22.NB.ultimo.docx)

**Comment by sebastianmtralcal** [comment]
No se hará el cambio debido a que toca una regla de negocio del cual no se tiene claridad de como debiese ir

**Comment by nataliabastias** [comment]
PENDENTE QA, los pedidos deben tener los mismos validadores al momento de editar

**Comment by nataliabastias** [comment]
QA ambiente QA OK

**Comment by nataliabastias** [comment]
OK ambiente PRODUCTIVO probado en el perfil gerente comercial
