### ISSUE TITLE
SOW Fletes, Distancia y Tiempos: Fórmulas Tarifas Flete

### ISSUE THREAD

**Issue by nataliabastias** [rhasbun1/qlnow#539]
QA PRODUCTIVO
No se visualiza bien el mensaje, se debe reducir el tamaño de la pantalla para visualizar los botones.

![image](https://user-images.githubusercontent.com/91262410/186254315-00ffda38-9e74-4cb7-b037-2291c519eceb.png)

**Comment by sebastianmtralcal** [comment]
Se  cambia tamaño de texto

**Comment by Ditassara** [comment]
Cambios confirmados en ambiente QA.

![image](https://user-images.githubusercontent.com/56659426/186443389-91abefd1-bf46-4a02-aac6-1d6055b56afc.png)

**Comment by Ditassara** [comment]
El mensaje no está apareciendo en Productivo y en QA, no sé que habrá ocurrido, revisar.

**Comment by sebastianmtralcal** [comment]
![image](https://user-images.githubusercontent.com/86976515/197211962-83fab05e-b95c-4d34-9d7b-919f1bf0f408.png)

Se disminuye el tamaño de la letra

**Comment by nataliabastias** [comment]
OK amiente QA
