### ISSUE TITLE
Requerimiento 220 Validador Pedido fuera de plazo.

### ISSUE THREAD

**Issue by nataliabastias** [rhasbun1/qlnow#548]
cuando es formato retira igual le suma el tiempo de traslado como si fuera en obra.

![image](https://user-images.githubusercontent.com/91262410/189412842-0935540f-e40a-4ef2-9340-5364d8e2b548.png)

**Comment by sebastianmtralcal** [comment]
Problema resuelto al editar

**Comment by nataliabastias** [comment]
ok QA ambiente QA

**Comment by nataliabastias** [comment]
ok ambiente productivo probado con perfil gerente comercial
