### ISSUE TITLE
Requerimiento 225 observación

### ISSUE THREAD

**Issue by nataliabastias** [rhasbun1/qlnow#554]
No se están restableciendo correctamente los valores predefinidos de Planta de Origen y Forma de Entrega. Ejemplo NV 4836. Si cambio planta de origen y/o forma de entrega prestablecido de uno o más productos, al crear un segundo y tercer predefinido consecutivo no se devuelve a los valores predefinidos de cada producto. NUEVAMENTE SE REPITE ESTA OBSERVACIÓN!!

Ya identificado en el registro 442

**Comment by nataliabastias** [comment]
PEDNDIENTE

**Comment by sebastianmtralcal** [comment]
Problema resuelto

**Comment by nataliabastias** [comment]
OK ambiente QA

**Comment by nataliabastias** [comment]
OK ambiente PRODUCTIVO probado en el perfil gerente comercial
