### ISSUE TITLE
SOW Fletes, Distancia y Tiempos: Fórmulas tarifas Flete

### ISSUE THREAD

**Issue by nataliabastias** [rhasbun1/qlnow#567]
Según SOW  en la fórmulas tarifas Flete debe mostrar "...Se visualizarán los tipos de unidades de medidas según el maestro “Productos”... "
No se visualizan las mismas unidades de medidas ejemplo "Maxisaco"

![image](https://user-images.githubusercontent.com/91262410/193074743-a32ed39d-84a3-4417-a09b-3b9e41792e8a.png)

![image](https://user-images.githubusercontent.com/91262410/193074929-8acdf782-755b-4a20-8d79-586937c767c6.png)

![image](https://user-images.githubusercontent.com/91262410/193074852-e93ceb7a-a22c-47bb-8565-d88b9b60b6cd.png)

**Comment by sebastianmtralcal** [comment]
http://localhost/qlnow/listaProductos

**Comment by sebastianmtralcal** [comment]
[spGetTarifasFletesPorAno.txt](https://github.com/rhasbun1/qlnow/files/9860990/spGetTarifasFletesPorAno.txt)


Se modifica procedimiento almacenado para que muestre la unidad faltante

**Comment by nataliabastias** [comment]
OK Ambiente QA
